'use client';
import { useEffect, useRef, useState } from 'react';
import { Plus, MapPin, ToggleLeft, ToggleRight, Pencil, Trash2, Package, X, Save, Search, Users, ShoppingCart, Activity, Truck, CheckCircle2, Clock3 } from 'lucide-react';
import { loadGoogleMaps } from '../../../lib/mapsLoader';
import AdminShell from '../../../components/AdminShell';
import { getMarkets, getMarketDashboard, createMarket, updateMarket } from '../../../lib/api/admin';
import { api } from '../../../lib/api/client';

type Product = { id:string; name:string; description?:string; price:number; referenceCost:number; stock:number; imageUrl?:string|null; available:boolean; status:string };
type Market = { id:string; name:string; description?:string; address:string; pickupContactName?:string; pickupPhone:string; lat:number; lng:number; active:boolean; agents?:any[]; products?:Product[] };
type Dashboard = { market:any; metrics:any; agents:any[]; recentOrders:any[] };

const emptyMarket={name:'',description:'',address:'',pickupContactName:'',pickupPhone:'',lat:'',lng:''};
const emptyProduct={name:'',description:'',referenceCost:'',stock:'0',imageBase64:'',imageUrl:''};

export default function MarketsPage(){
 const [markets,setMarkets]=useState<Market[]>([]); const [showForm,setShowForm]=useState(false); const [form,setForm]=useState<any>(emptyMarket);
 const [dashboard,setDashboard]=useState<Dashboard|null>(null); const [marketSearch,setMarketSearch]=useState('');
 const [selected,setSelected]=useState<Market|null>(null); const [productForm,setProductForm]=useState<any>(emptyProduct); const [editing,setEditing]=useState<string|null>(null);
 const [saving,setSaving]=useState(false); const [productSaving,setProductSaving]=useState(false); const mapRef=useRef<HTMLDivElement>(null); const searchRef=useRef<HTMLInputElement>(null); const map=useRef<any>(null); const marker=useRef<any>(null); const autocomplete=useRef<any>(null);

 const load=async()=>{try{const data=await getMarkets();setMarkets(data);if(selected){const fresh=data.find((m:any)=>m.id===selected.id);if(fresh)setSelected(fresh);}}catch{}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!selected)return;const refresh=async()=>{try{setDashboard(await getMarketDashboard(selected.id))}catch{setDashboard(null)}};refresh();const timer=setInterval(refresh,15000);return()=>clearInterval(timer)},[selected?.id]);
 useEffect(()=>{if(!showForm)return;loadGoogleMaps().then(()=>{if(!mapRef.current)return;const G=(window as any).google.maps;const center=form.lat&&form.lng?{lat:Number(form.lat),lng:Number(form.lng)}:{lat:-1.9536,lng:30.0605};map.current=new G.Map(mapRef.current,{center,zoom:form.lat?16:12.5,streetViewControl:false,mapTypeControl:false,fullscreenControl:true});const place=(lat:number,lng:number)=>{if(marker.current)marker.current.setMap(null);marker.current=new G.Marker({map:map.current,position:{lat,lng},draggable:true});map.current.panTo({lat,lng});setForm((f:any)=>({...f,lat:lat.toFixed(6),lng:lng.toFixed(6)}));marker.current.addListener('dragend',(e:any)=>setForm((f:any)=>({...f,lat:e.latLng.lat().toFixed(6),lng:e.latLng.lng().toFixed(6)})))};if(form.lat&&form.lng)place(Number(form.lat),Number(form.lng));map.current.addListener('click',(e:any)=>place(e.latLng.lat(),e.latLng.lng()));if(searchRef.current&&G.places?.Autocomplete){autocomplete.current=new G.places.Autocomplete(searchRef.current,{componentRestrictions:{country:'rw'},fields:['geometry','formatted_address','name']});autocomplete.current.addListener('place_changed',()=>{const p=autocomplete.current.getPlace();if(!p.geometry?.location)return;const lat=p.geometry.location.lat(),lng=p.geometry.location.lng();place(lat,lng);setForm((f:any)=>({...f,address:p.formatted_address||f.address}))})}}).catch(()=>{});return()=>{if(marker.current)marker.current.setMap(null);marker.current=null;map.current=null;autocomplete.current=null}},[showForm]);

 const handleCreate=async()=>{setSaving(true);try{const body={name:String(form.name||''),description:String(form.description||''),address:String(form.address||''),pickupContactName:String(form.pickupContactName||''),pickupPhone:String(form.pickupPhone||''),lat:Number(form.lat),lng:Number(form.lng)};if(form.id)await updateMarket(form.id,body);else await createMarket(body);setShowForm(false);setForm(emptyMarket);await load();if(selected)await getMarketDashboard(selected.id)}finally{setSaving(false)}};
 const openEdit=(m:Market)=>{setForm({...m,lat:String(m.lat),lng:String(m.lng)});setShowForm(true)};
 const openMarket=(m:Market)=>{setSelected(m);setEditing(null);setProductForm(emptyProduct)};
 const openAdd=()=>{setEditing(null);setProductForm(emptyProduct)};
 const editProduct=(p:Product)=>{setEditing(p.id);setProductForm({name:p.name,description:p.description||'',referenceCost:String(p.referenceCost),stock:String(p.stock??0),imageBase64:'',imageUrl:p.imageUrl||''})};
 const image=(e:any)=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>setProductForm((v:any)=>({...v,imageBase64:String(reader.result)}));reader.readAsDataURL(file)};
 const saveProduct=async()=>{if(!selected)return;setProductSaving(true);try{const body:any={name:productForm.name,description:productForm.description,referenceCost:Number(productForm.referenceCost),stock:Number(productForm.stock)};if(productForm.imageBase64)body.imageBase64=productForm.imageBase64;if(editing){await api.patch('/admin/markets/'+selected.id+'/products/'+editing,body)}else{await api.post('/admin/markets/'+selected.id+'/products',body)}setProductForm(emptyProduct);setEditing(null);await load()}finally{setProductSaving(false)}};
 const disableProduct=async(id:string)=>{if(!selected||!confirm('Disable this market good?'))return;await api.delete('/admin/markets/'+selected.id+'/products/'+id);await load();await getMarketDashboard(selected.id)};
 const filteredMarkets=markets.filter(m=>(m.name+' '+m.address).toLowerCase().includes(marketSearch.toLowerCase()));
 return <AdminShell><div>
  <div className="flex items-center justify-between mb-5"><div><h1 className="text-2xl font-bold text-gray-900">Markets</h1><p className="text-sm text-gray-500 mt-1">Location, inventory, agents and live market operations.</p></div><button onClick={()=>{setForm(emptyMarket);setShowForm(true)}} className="flex items-center gap-1.5 bg-zana-primary text-white font-semibold px-4 py-2 rounded-lg text-sm"><Plus size={15}/> Add Market</button></div>
  <div className="bg-white rounded-xl p-3 mb-4 border border-gray-100 flex items-center gap-2"><Search size={17} className="text-gray-400"/><input value={marketSearch} onChange={e=>setMarketSearch(e.target.value)} placeholder="Search markets" className="flex-1 outline-none text-sm"/></div>
  {showForm&&<div className="bg-white rounded-xl p-5 shadow-sm mb-5"><div className="flex items-center justify-between mb-3"><div><h2 className="font-semibold text-gray-900">{form.id?'Edit market':'New market'}</h2><p className="text-xs text-gray-500">Search the map and drag the pin to the exact pickup location.</p></div><button onClick={()=>setShowForm(false)}><X size={18}/></button></div><div className="grid grid-cols-2 gap-3">{[['name','Market name'],['description','Description'],['address','Address'],['pickupContactName','Pickup contact name'],['pickupPhone','Pickup phone']].map(([k,p])=><input key={k} value={(form as any)[k]} onChange={e=>setForm((v:any)=>({...v,[k]:e.target.value}))} placeholder={p} className="border border-gray-200 rounded-lg px-3 py-2 text-sm"/>)}</div><div className="mt-4"><div className="relative mb-2"><Search className="absolute left-3 top-2.5 text-gray-400" size={16}/><input ref={searchRef} placeholder="Search market or address in Rwanda" className="w-full border border-gray-200 rounded-lg pl-9 pr-3 py-2.5 text-sm"/></div><div className="flex items-center justify-between mb-2"><p className="text-xs font-bold text-gray-700">Exact pickup location</p><span className="text-[10px] text-gray-400">{form.lat&&form.lng?form.lat+', '+form.lng:'Select a pin'}</span></div><div ref={mapRef} className="h-64 rounded-xl border border-gray-200 overflow-hidden bg-gray-100"/><p className="text-[10px] text-gray-400 mt-2">Click the map or drag the pin after searching to correct the exact entrance.</p></div><div className="flex gap-2 mt-3"><button onClick={handleCreate} disabled={saving||!form.name||!form.address||!form.pickupPhone||!form.lat||!form.lng} className="bg-zana-primary text-white font-semibold px-4 py-2 rounded-lg text-sm disabled:opacity-40">{saving?'Saving…':'Save Market'}</button><button onClick={()=>setShowForm(false)} className="border border-gray-200 text-gray-600 px-4 py-2 rounded-lg text-sm">Cancel</button></div></div>}
  <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{filteredMarkets.map(m=><div key={m.id} className="bg-white rounded-xl p-4 shadow-sm"><div className="flex items-start justify-between"><button onClick={()=>openMarket(m)} className="text-left flex-1"><p className="font-semibold text-gray-900">{m.name}</p><p className="text-xs text-gray-500 flex items-center gap-1 mt-1"><MapPin size={11}/>{m.address}</p>{m.description&&<p className="text-xs text-gray-500 mt-1">{m.description}</p>}<p className="text-xs text-gray-500 mt-2"><Package size={11} className="inline mr-1"/>{m.products?.length??0} goods · {m.agents?.length??0} agents</p></button><button onClick={()=>updateMarket(m.id,{active:!m.active}).then(load)} className={m.active?'text-green-600':'text-gray-400'}>{m.active?<ToggleRight size={22}/>:<ToggleLeft size={22}/>}</button></div><div className="flex gap-2 mt-3"><button onClick={()=>openMarket(m)} className="flex-1 border border-gray-200 rounded-lg py-2 text-sm font-semibold text-gray-700">Open dashboard</button><button onClick={()=>openEdit(m)} className="border border-gray-200 rounded-lg px-3"><Pencil size={15}/></button></div></div>)}</div>

  {selected&&<div className="fixed inset-0 z-50 bg-black/40 p-4 md:p-8 overflow-auto"><div className="max-w-6xl mx-auto bg-gray-50 rounded-2xl min-h-full shadow-xl"><div className="bg-white rounded-t-2xl p-5 flex items-center justify-between sticky top-0 z-10"><div><h2 className="text-xl font-bold text-gray-900">{selected.name}</h2><p className="text-xs text-gray-500 flex items-center gap-1 mt-1"><MapPin size={11}/>{selected.address} · {selected.lat.toFixed(6)}, {selected.lng.toFixed(6)}</p></div><div className="flex gap-2"><button onClick={()=>openEdit(selected)} className="border border-gray-200 rounded-lg px-3 py-2 text-xs font-semibold flex items-center gap-1"><Pencil size={13}/> Location</button><button onClick={()=>setSelected(null)} className="p-2 text-gray-500"><X/></button></div></div>
   {dashboard&&<div className="p-5 pb-0"><div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3">{[['Agents',dashboard.metrics.activeAgents+'/'+dashboard.metrics.totalAgents,Users],['Orders today',dashboard.metrics.ordersToday,ShoppingCart],['Processing',dashboard.metrics.processingOrders,Activity],['Items processing',dashboard.metrics.processingItems,Package],['Ready',dashboard.metrics.readyForPickup,Clock3],['Delivery',dashboard.metrics.outForDelivery,Truck],['Delivered',dashboard.metrics.deliveredToday,CheckCircle2],['Goods',dashboard.metrics.totalProducts,Package]].map(([label,value,Icon]:any)=><div key={label} className="bg-white rounded-xl p-3 border border-gray-100"><Icon size={17} className="text-zana-primary mb-2"/><p className="text-lg font-bold text-gray-900">{value}</p><p className="text-[11px] text-gray-500">{label}</p></div>)}</div></div>}
   {dashboard&&<div className="p-5 pb-0 grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 bg-white rounded-xl p-4 border border-gray-100"><div className="flex items-center justify-between mb-3"><h3 className="font-bold text-gray-900">Live processing</h3><span className="text-[10px] text-gray-400">Refreshes every 15s</span></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="text-gray-400 border-b"><th className="py-2">Order</th><th>Status</th><th>Items</th><th>Value</th><th>Agent</th></tr></thead><tbody>{dashboard.recentOrders.map((o:any)=><tr key={o.id} className="border-b last:border-0"><td className="py-2 font-semibold">{o.id.slice(0,8)}</td><td><span className="px-2 py-1 rounded-full bg-gray-100">{o.status}</span></td><td>{o.items.reduce((s:any,i:any)=>s+i.quantity,0)}</td><td>{Number(o.total).toLocaleString()} RWF</td><td>{o.agentId?o.agentId.slice(0,8):'Unassigned'}</td></tr>)}</tbody></table></div></div><div className="bg-white rounded-xl p-4 border border-gray-100"><h3 className="font-bold text-gray-900 mb-3">Agents</h3><div className="space-y-2 max-h-72 overflow-auto">{dashboard.agents.map((a:any)=><div key={a.id} className="flex items-center justify-between border-b last:border-0 pb-2"><div><p className="text-sm font-semibold">{a.firstName} {a.lastName}</p><p className="text-[11px] text-gray-500">{a.phone||'No phone'}</p></div><div className="text-right text-[10px]"><p className={a.shopping?'text-amber-600 font-semibold':a.working?'text-green-600 font-semibold':'text-gray-400'}>{a.shopping?'Shopping':a.working?'Working':'Available'}</p><p>{a.active?'Active':'Inactive'}</p></div></div>)}</div></div></div>}
   <div className="p-5 grid lg:grid-cols-3 gap-5"><div className="lg:col-span-1 bg-white rounded-xl p-4 h-fit"><h3 className="font-bold text-gray-900 mb-4">Add good</h3><div className="space-y-3"><input value={productForm.name} onChange={e=>setProductForm((v:any)=>({...v,name:e.target.value}))} placeholder="Good name" className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm"/><input type="number" min="1" value={productForm.referenceCost} onChange={e=>setProductForm((v:any)=>({...v,referenceCost:e.target.value}))} placeholder="Reference cost (RWF)" className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm"/><input type="number" min="0" value={productForm.stock} onChange={e=>setProductForm((v:any)=>({...v,stock:e.target.value}))} placeholder="Stock / quantity" className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm"/><input type="file" accept="image/*" onChange={image} className="w-full text-xs"/><button onClick={saveProduct} disabled={productSaving||!productForm.name||Number(productForm.referenceCost)<=0} className="w-full bg-zana-primary text-white font-semibold px-3 py-2.5 rounded-lg disabled:opacity-40">{productSaving ? 'Saving...' : 'Add good'}</button></div></div>
   <div className="lg:col-span-2"><h3 className="font-bold text-gray-900 mb-3">Market goods</h3><div className="grid sm:grid-cols-2 gap-3">{(selected.products||[]).map((p:Product)=><div key={p.id} className="bg-white rounded-xl p-4 border border-gray-100"><div className="flex gap-3">{p.imageUrl ? <img src={p.imageUrl} className="w-20 h-20 rounded-lg object-cover" alt=""/> : <div className="w-20 h-20 rounded-lg bg-gray-100 flex items-center justify-center"><Package size={22} className="text-gray-400"/></div>}<div className="min-w-0 flex-1"><p className="font-semibold text-gray-900 truncate">{p.name}</p><p className="text-xs text-gray-500 mt-1">Cost: {Number(p.referenceCost).toLocaleString()} RWF</p><p className="text-sm font-bold text-zana-primary mt-1">Customer: {Number(p.price).toLocaleString()} RWF</p><p className="text-xs text-gray-500 mt-1">Stock: {p.stock} · {p.available ? 'Available' : 'Unavailable'}</p></div></div><div className="flex gap-2 mt-3"><button onClick={()=>editProduct(p)} className="flex-1 border border-gray-200 rounded-lg py-2 text-xs font-semibold"><Pencil size={13}/> Edit</button><button onClick={()=>disableProduct(p.id)} className="border border-red-100 text-red-600 rounded-lg px-3 py-2 text-xs"><Trash2 size={13}/></button></div></div>)}</div>{!(selected.products||[]).length && <div className="bg-white rounded-xl p-10 text-center text-sm text-gray-500">No goods in this market yet.</div>}</div>
  </div></div></div>}
 </div></AdminShell>;
}
