'use client';

export type Lang = 'en' | 'fr' | 'rw';

const STORAGE_KEY = 'zana_lang';

export const LANG_LABELS: Record<Lang, string> = {
  en: 'English',
  fr: 'Français',
  rw: 'Ikinyarwanda',
};

export function getStoredLang(): Lang {
  if (typeof window === 'undefined') return 'en';
  return (localStorage.getItem(STORAGE_KEY) as Lang) ?? 'rw';
}

export function setStoredLang(lang: Lang) {
  if (typeof window === 'undefined') return;
  localStorage.setItem(STORAGE_KEY, lang);
}

// UI strings for the customer app in all three languages.
export const UI: Record<string, Record<Lang, string>> = {
  'What do you need today?': { en: 'What do you need today?', fr: 'Que voulez-vous aujourd\'hui?', rw: 'Ukeneye iki uyu munsi?' },
  'Wallet Balance': { en: 'Wallet Balance', fr: 'Solde du portefeuille', rw: 'Amafaranga afite' },
  'Top Up': { en: 'Top Up', fr: 'Recharger', rw: 'Shyiramo amafaranga' },
  'Send My Location': { en: 'Send My Location', fr: 'Envoyer ma localisation', rw: 'Ohereza aho ndi' },
  'Share a code instead of explaining your address': { en: 'Share a code instead of explaining your address', fr: 'Partagez un code au lieu d\'expliquer votre adresse', rw: 'Ohereza kode aho gusobanura aho uri' },
  'Orders': { en: 'Orders', fr: 'Commandes', rw: 'Ibyagurijwe' },
  'Wallet': { en: 'Wallet', fr: 'Portefeuille', rw: 'Amafaranga' },
  'Profile': { en: 'Profile', fr: 'Profil', rw: 'Umwirondoro' },
  'Home': { en: 'Home', fr: 'Accueil', rw: 'Ahabanza' },
  'Chat': { en: 'Chat', fr: 'Discussion', rw: 'Ganira' },
  'Send': { en: 'Send', fr: 'Envoyer', rw: 'Ohereza' },
  'Type a message…': { en: 'Type a message…', fr: 'Écrivez un message…', rw: 'Andika ubutumwa…' },
  'Language': { en: 'Language', fr: 'Langue', rw: 'Ururimi' },
};

export function t(key: string, lang: Lang): string {
  return UI[key]?.[lang] ?? key;
}

// Driver-specific UI strings
export const DRIVER_UI: Record<string, Record<Lang, string>> = {
  'Go Online': { en: 'Go Online', fr: 'Se connecter', rw: 'Injira kumurongo' },
  'Go Offline': { en: 'Go Offline', fr: 'Se déconnecter', rw: 'Sohoka kumurongo' },
  'You are online': { en: 'You are online', fr: 'Vous êtes en ligne', rw: 'Uri kumurongo' },
  'You are offline': { en: 'You are offline', fr: 'Vous êtes hors ligne', rw: 'Ntabwo uri kumurongo' },
  'Earnings': { en: 'Earnings', fr: 'Revenus', rw: 'Inyungu' },
  'Today': { en: 'Today', fr: 'Aujourd\'hui', rw: 'Uyu munsi' },
  'All time': { en: 'All time', fr: 'Tout le temps', rw: 'Igihe cyose' },
  'Trips': { en: 'Trips', fr: 'Trajets', rw: 'Ingendo' },
  'Accept': { en: 'Accept', fr: 'Accepter', rw: 'Emera' },
  'Decline': { en: 'Decline', fr: 'Refuser', rw: 'Ima' },
  'I\'ve Arrived': { en: 'I\'ve Arrived', fr: 'Je suis arrivé', rw: 'Nashe' },
  'Start Trip': { en: 'Start Trip', fr: 'Démarrer le trajet', rw: 'Tangira urugendo' },
  'Complete Trip': { en: 'Complete Trip', fr: 'Terminer le trajet', rw: 'Rangiza urugendo' },
  'Heading to pickup': { en: 'Heading to pickup', fr: 'En route vers le client', rw: 'Ngiye guterura' },
  'Waiting for passenger': { en: 'Waiting for passenger', fr: 'En attente du passager', rw: 'Ndinda umugeni' },
  'Trip in progress': { en: 'Trip in progress', fr: 'Trajet en cours', rw: 'Urugendo rurakomeza' },
  'New ride request': { en: 'New ride request', fr: 'Nouvelle demande de trajet', rw: 'Gusaba urugendo gushya' },
  'away': { en: 'away', fr: 'de distance', rw: 'hari' },
  'Fare': { en: 'Fare', fr: 'Tarif', rw: 'Igiciro' },
  'What do you want to receive?': { en: 'What do you want to receive?', fr: 'Que voulez-vous recevoir?', rw: 'Urashaka guhabwa iki?' },
  'Rides only': { en: 'Rides only', fr: 'Trajets seulement', rw: 'Ingendo gusa' },
  'Deliveries only': { en: 'Deliveries only', fr: 'Livraisons seulement', rw: 'Kohereza gusa' },
  'Both': { en: 'Both', fr: 'Les deux', rw: 'Byombi' },

  'Earnings & Wallet': { en: 'Earnings & Wallet', fr: 'Revenus et portefeuille', rw: 'Inyungu n\'Amafaranga' },
  '15% platform commission applies to all earnings': { en: '15% platform commission applies to all earnings', fr: 'Une commission de 15% s\'applique à tous les revenus', rw: '15% by amafaranga yose ni komisiyo ya Zana' },
  'Balance owed to Zana': { en: 'Balance owed to Zana', fr: 'Solde dû à Zana', rw: 'Amafaranga ubereyemo Zana' },
  'Available to withdraw': { en: 'Available to withdraw', fr: 'Disponible pour retrait', rw: 'Ushobora gukura' },
  'in wallet': { en: 'in wallet', fr: 'dans le portefeuille', rw: 'mu mafaranga afite' },
  'owed from cash rides': { en: 'owed from cash rides', fr: 'dû des trajets en espèces', rw: 'ubereyemo ku ngendo z\'amafaranga y\'ikiganza' },
  'After 15% Zana commission deducted': { en: 'After 15% Zana commission deducted', fr: 'Après déduction de la commission Zana de 15%', rw: 'Nyuma yo gukurwamo 15% ya komisiyo ya Zana' },
  'Pay now with MoMo': { en: 'Pay now with MoMo', fr: 'Payer maintenant avec MoMo', rw: 'Ishyura ubu na MoMo' },
  'Today\'s earnings': { en: 'Today\'s earnings', fr: 'Revenus d\'aujourd\'hui', rw: 'Inyungu z\'uyu munsi' },
  'Cash collected today': { en: 'Cash collected today', fr: 'Espèces collectées aujourd\'hui', rw: 'Amafaranga y\'ikiganza yakiriwe uyu munsi' },
  'This week': { en: 'This week', fr: 'Cette semaine', rw: 'Iki cyumweru' },
  'Total earned': { en: 'Total earned', fr: 'Total gagné', rw: 'Byose winjije' },
  'Recent Zana due': { en: 'Recent Zana due', fr: 'Dettes Zana récentes', rw: 'Amafaranga ubereyemo Zana vuba' },
  'Activity': { en: 'Activity', fr: 'Activité', rw: 'Ibikorwa' },
  'Rides': { en: 'Rides', fr: 'Trajets', rw: 'Ingendo' },
  'Deliveries': { en: 'Deliveries', fr: 'Livraisons', rw: 'Ibyoherejwe' },
  'Withdraw to Mobile Money': { en: 'Withdraw to Mobile Money', fr: 'Retirer vers Mobile Money', rw: 'Kura amafaranga kuri Mobile Money' },
  'Withdrawal sent! Check your phone.': { en: 'Withdrawal sent! Check your phone.', fr: 'Retrait envoyé! Vérifiez votre téléphone.', rw: 'Gukura amafaranga byoherejwe! Reba kuri telefoni yawe.' },
  'Amount (RWF)': { en: 'Amount (RWF)', fr: 'Montant (RWF)', rw: 'Amafaranga (RWF)' },
  'Min 1,000 RWF': { en: 'Min 1,000 RWF', fr: 'Min 1 000 RWF', rw: 'Nibura 1,000 RWF' },
  'MTN / Airtel number': { en: 'MTN / Airtel number', fr: 'Numéro MTN / Airtel', rw: 'Numero ya MTN / Airtel' },
  'Processing…': { en: 'Processing…', fr: 'Traitement en cours…', rw: 'Birimo gukorwa…' },
  'Withdraw': { en: 'Withdraw', fr: 'Retirer', rw: 'Kura amafaranga' },
  'Withdrawals are processed via Paypack MoMo': { en: 'Withdrawals are processed via Paypack MoMo', fr: 'Les retraits sont traités via Paypack MoMo', rw: 'Gukura amafaranga bikorwa binyuze kuri Paypack MoMo' },
  'Pay Zana': { en: 'Pay Zana', fr: 'Payer Zana', rw: 'Ishyura Zana' },
  'the full amount currently due': { en: 'the full amount currently due', fr: 'le montant total actuellement dû', rw: 'amafaranga yose asigaye ubu' },
  'Pay now': { en: 'Pay now', fr: 'Payer maintenant', rw: 'Ishyura ubu' },
  'Check your phone': { en: 'Check your phone', fr: 'Vérifiez votre téléphone', rw: 'Reba kuri telefoni yawe' },
  'Approve the MoMo prompt to complete payment': { en: 'Approve the MoMo prompt to complete payment', fr: 'Approuvez la demande MoMo pour terminer le paiement', rw: 'Emeza ubutumwa bwa MoMo kugira ngo urangize kwishyura' },
  'Payment received': { en: 'Payment received', fr: 'Paiement reçu', rw: 'Ubwishyu bwakiriwe' },
  'Your Zana due balance is now settled': { en: 'Your Zana due balance is now settled', fr: 'Votre solde dû à Zana est maintenant réglé', rw: 'Amafaranga wari ubereyemo Zana yarishyuwe' },
  'Done': { en: 'Done', fr: 'Terminé', rw: 'Byarangiye' },
  'Payment didn\'t go through': { en: 'Payment didn\'t go through', fr: 'Le paiement n\'a pas abouti', rw: 'Ubwishyu ntibwagenze neza' },
  'Try again': { en: 'Try again', fr: 'Réessayer', rw: 'Ongera ugerageze' },
  'Minimum withdrawal is 10,000 RWF': { en: 'Minimum withdrawal is 10,000 RWF', fr: 'Le retrait minimum est de 10 000 RWF', rw: 'Ubuke bwo gukura ni 10,000 RWF' },
  'Insufficient balance': { en: 'Insufficient balance', fr: 'Solde insuffisant', rw: 'Amafaranga ntahagije' },
  'Enter a valid phone number': { en: 'Enter a valid phone number', fr: 'Entrez un numéro de téléphone valide', rw: 'Andika numero ya telefoni nyayo' },
  'Withdrawal failed. Try again.': { en: 'Withdrawal failed. Try again.', fr: 'Le retrait a échoué. Réessayez.', rw: 'Gukura amafaranga byanze. Ongera ugerageze.' },
  'Could not reach the payment provider.': { en: 'Could not reach the payment provider.', fr: 'Impossible de joindre le fournisseur de paiement.', rw: 'Ntibyashobotse guhuza n\'uwishyura.' },
  '← Back': { en: '← Back', fr: '← Retour', rw: '← Subira inyuma' },
  'Your documents': { en: 'Your documents', fr: 'Vos documents', rw: 'Ibyangombwa byawe' },
  'Manage': { en: 'Manage', fr: 'Gérer', rw: 'Gucunga' },
  'rating': { en: 'rating', fr: 'note', rw: 'amanota' },
  'Outstanding commission debt': { en: 'Outstanding commission debt', fr: 'Dette de commission en cours', rw: 'Amafaranga y\'ikomisiyo usigaje' },
  'You owe': { en: 'You owe', fr: 'Vous devez', rw: 'Ubereyemo' },
  'in commission from': { en: 'in commission from', fr: 'en commission provenant de', rw: 'ku ikomisiyo iva ku' },
  'cash trip': { en: 'cash trip', fr: 'trajet en espèces', rw: 'urugendo rw\'amafaranga y\'ikiganza' },
  'cash trips': { en: 'cash trips', fr: 'trajets en espèces', rw: 'ingendo z\'amafaranga y\'ikiganza' },
  'This will be deducted from your next wallet earning.': { en: 'This will be deducted from your next wallet earning.', fr: 'Ceci sera déduit de votre prochain revenu.', rw: 'Ibi bizakurwa ku nyungu yawe ikurikira.' },
  '💡 Tip: Keep at least 5,000 RWF in your wallet to avoid debt.': { en: '💡 Tip: Keep at least 5,000 RWF in your wallet to avoid debt.', fr: '💡 Astuce: Gardez au moins 5 000 RWF pour éviter les dettes.', rw: '💡 Inama: Gumana nibura 5,000 RWF kugira ngo wirinde imyenda.' },
  'No outstanding debt — you\'re all clear!': { en: 'No outstanding debt — you\'re all clear!', fr: 'Aucune dette en cours — tout est en ordre!', rw: 'Nta myenda usigaje — byose biri neza!' },
  'Total rides': { en: 'Total rides', fr: 'Total des trajets', rw: 'Ingendo zose' },
  'Rating': { en: 'Rating', fr: 'Note', rw: 'Amanota' },
  'Member since': { en: 'Member since', fr: 'Membre depuis', rw: 'Yinjiye kuva' },
  '❌ Account rejected': { en: '❌ Account rejected', fr: '❌ Compte rejeté', rw: '❌ Konti yanzwe' },
  '⏳ Pending approval': { en: '⏳ Pending approval', fr: '⏳ En attente d\'approbation', rw: '⏳ Bitegereje kwemezwa' },
  'Reason': { en: 'Reason', fr: 'Raison', rw: 'Impamvu' },
  'Please contact support@zana.rw to appeal.': { en: 'Please contact support@zana.rw to appeal.', fr: 'Veuillez contacter support@zana.rw pour faire appel.', rw: 'Nyamuneka hamagara support@zana.rw kugira ngo wiyambaze.' },
  'Recent ratings from passengers': { en: 'Recent ratings from passengers', fr: 'Notes récentes des passagers', rw: 'Amanota aherutse aturuka ku bagenzi' },
  'Language': { en: 'Language', fr: 'Langue', rw: 'Ururimi' },
  'Log out': { en: 'Log out', fr: 'Se déconnecter', rw: 'Sohoka' },
  'Your rides': { en: 'Your rides', fr: 'Vos trajets', rw: 'Ingendo zawe' },
  'Loading…': { en: 'Loading…', fr: 'Chargement…', rw: 'Birimo gupakira…' },
  'No rides yet': { en: 'No rides yet', fr: 'Aucun trajet pour le moment', rw: 'Nta rugendo urahagira' },
  'Completed': { en: 'Completed', fr: 'Terminé', rw: 'Byarangiye' },
  'Cancelled by passenger': { en: 'Cancelled by passenger', fr: 'Annulé par le passager', rw: "Byahagaritswe n'umugenzi" },
  'You cancelled': { en: 'You cancelled', fr: 'Vous avez annulé', rw: 'Wabikuyeho' },
  'Delivery pool': { en: 'Delivery pool', fr: 'Ibicuruzwa byo kohereza', rw: 'Ibicuruzwa byo kohereza' },
  'Pick jobs that fit your route. Up to 3 at a time.': { en: 'Pick jobs that fit your route. Up to 3 at a time.', fr: 'Hitamo imirimo ijyanye n\'inzira yawe. Kugeza kuri 3 icyarimwe.', rw: 'Hitamo imirimo ijyanye n\'inzira yawe. Kugeza kuri 3 icyarimwe.' },
  'Carrying': { en: 'Carrying', fr: 'Utwaye', rw: 'Utwaye' },
  'parcel': { en: 'parcel', fr: 'ipaki', rw: 'ipaki' },
  'parcels': { en: 'parcels', fr: 'amapaki', rw: 'amapaki' },
  'On board': { en: 'On board', fr: 'Biri kuri moto', rw: 'Biri kuri moto' },
  'To collect': { en: 'To collect', fr: 'Gutora', rw: 'Gutora' },
  'Tap to continue →': { en: 'Tap to continue →', fr: 'Kanda ukomeze →', rw: 'Kanda ukomeze →' },
  'No deliveries waiting near you': { en: 'No deliveries waiting near you', fr: 'Nta bicuruzwa bitegereje hafi yawe', rw: 'Nta bicuruzwa bitegereje hafi yawe' },
  'URGENT': { en: 'URGENT', fr: 'BYIHUTIRWA', rw: 'BYIHUTIRWA' },
  'km away': { en: 'km away', fr: 'km uvuye', rw: 'km uvuye' },
  'waiting': { en: 'waiting', fr: 'byategereje', rw: 'byategereje' },
  'min': { en: 'min', fr: 'iminota', rw: 'iminota' },
  'km detour': { en: 'km detour', fr: 'km y\'inzira indi', rw: 'km y\'inzira indi' },
  'Accepting…': { en: 'Accepting…', fr: 'Byemejwe…', rw: 'Byemejwe…' },
  'Accept delivery': { en: 'Accept delivery', fr: 'Emeza gucuruza', rw: 'Emeza gucuruza' },
  'You are carrying the maximum of 3': { en: 'You are carrying the maximum of 3', fr: 'Utwaye byinshi kugeza kuri 3', rw: 'Utwaye byinshi kugeza kuri 3' },
  'Too far off your current route': { en: 'Too far off your current route', fr: 'Biri kure cyane y\'inzira yawe', rw: 'Biri kure cyane y\'inzira yawe' },
  'You are already carrying': { en: 'You are already carrying', fr: 'Umaze gutwara', rw: 'Umaze gutwara' },
  'parcels. Finish one before taking another.': { en: 'parcels. Finish one before taking another.', fr: 'amapaki. Rangiza rimwe mbere yo gufata irindi.', rw: 'amapaki. Rangiza rimwe mbere yo gufata irindi.' },
  'That job is': { en: 'That job is', fr: 'Uwo murimo uri', rw: 'Uwo murimo uri' },
  'km off your current route. Only jobs within': { en: 'km off your current route. Only jobs within', fr: 'km kure y\'inzira yawe. Imirimo iri gusa muri', rw: 'km kure y\'inzira yawe. Imirimo iri gusa muri' },
  'km can be added.': { en: 'km can be added.', fr: 'km ishobora kongerwaho.', rw: 'km ishobora kongerwaho.' },
  'Another rider took that one.': { en: 'Another rider took that one.', fr: 'Undi moto yamaze kuyifata.', rw: 'Undi moto yamaze kuyifata.' },
  'Could not accept that delivery.': { en: 'Could not accept that delivery.', fr: 'Ntibyakunze kwemeza icyo gicuruzwa.', rw: 'Ntibyakunze kwemeza icyo gicuruzwa.' },
  'No active delivery': { en: 'No active delivery', fr: 'Nta gicuruzwa gikorwa ubu', rw: 'Nta gicuruzwa gikorwa ubu' },
  'Browse deliveries': { en: 'Browse deliveries', fr: 'Reba ibicuruzwa', rw: 'Reba ibicuruzwa' },
  'Uploading photo…': { en: 'Uploading photo…', fr: 'Byoherejwe ifoto…', rw: 'Byoherejwe ifoto…' },
  'Proof of handling': { en: 'Proof of handling', fr: 'Icyemezo cy\'ifatwa', rw: 'Icyemezo cy\'ifatwa' },
  'Photo could not upload. Continuing without it.': { en: 'Photo could not upload. Continuing without it.', fr: 'Ifoto ntiyashoboye koherezwa. Turakomeza nta yo.', rw: 'Ifoto ntiyashoboye koherezwa. Turakomeza nta yo.' },
  'Could not confirm pickup. Please try again.': { en: 'Could not confirm pickup. Please try again.', fr: 'Ntibyakunze kwemeza gutora. Ongera ugerageze.', rw: 'Ntibyakunze kwemeza gutora. Ongera ugerageze.' },
  'Could not confirm delivery. Please try again.': { en: 'Could not confirm delivery. Please try again.', fr: 'Ntibyakunze kwemeza kohereza. Ongera ugerageze.', rw: 'Ntibyakunze kwemeza kohereza. Ongera ugerageze.' },
  'Active delivery restored': { en: 'Active delivery restored', fr: 'Igicuruzwa cyagarutswe', rw: 'Igicuruzwa cyagarutswe' },
  'Status: To collect': { en: 'Status: To collect', fr: 'Uko bihagaze: Gutora', rw: 'Uko bihagaze: Gutora' },
  'Status: Picked up': { en: 'Status: Picked up', fr: 'Uko bihagaze: Byatowe', rw: 'Uko bihagaze: Byatowe' },
  'Next stop: Pickup': { en: 'Next stop: Pickup', fr: 'Aho ujya: Gutora', rw: 'Aho ujya: Gutora' },
  'Next stop: Customer': { en: 'Next stop: Customer', fr: 'Aho ujya: Umukiriya', rw: 'Aho ujya: Umukiriya' },
  'Go to pickup location': { en: 'Go to pickup location', fr: 'Jya aho gutorera', rw: 'Jya aho gutorera' },
  'Deliver to customer': { en: 'Deliver to customer', fr: 'Twara ku mukiriya', rw: 'Twara ku mukiriya' },
  'Package': { en: 'Package', fr: 'Ipaki', rw: 'Ipaki' },
  'From:': { en: 'From:', fr: 'Biva:', rw: 'Biva:' },
  'Pickup': { en: 'Pickup', fr: 'Gutora', rw: 'Gutora' },
  'Dropoff': { en: 'Dropoff', fr: 'Kohereza', rw: 'Kohereza' },
  'Customer': { en: 'Customer', fr: 'Umukiriya', rw: 'Umukiriya' },
  'Your earnings': { en: 'Your earnings', fr: 'Inyungu yawe', rw: 'Inyungu yawe' },
  'm away — move closer to confirm': { en: 'm away — move closer to confirm', fr: 'm uvuye — hurira hafi kugira ngo wemeze', rw: 'm uvuye — hurira hafi kugira ngo wemeze' },
  'Navigate': { en: 'Navigate', fr: 'Yobora', rw: 'Yobora' },
  'Confirm Pickup': { en: 'Confirm Pickup', fr: 'Emeza Gutora', rw: 'Emeza Gutora' },
  'Confirm Delivery': { en: 'Confirm Delivery', fr: 'Emeza Kohereza', rw: 'Emeza Kohereza' },
  'Stop': { en: 'Stop', fr: 'Aho uhagarara', rw: 'Aho uhagarara' },
};

export function dt(key: string, lang: Lang): string {
  return DRIVER_UI[key]?.[lang] ?? UI[key]?.[lang] ?? key;
}

// ⚠️ The Kinyarwanda entries below are best-effort machine translations,
// not reviewed by a native speaker — flagged here clearly so whoever
// reviews this knows exactly which block needs a real pass before
// trusting it in front of drivers. The entries above this line (the
// original DRIVER_UI set) were already in the codebase before this and
// are not part of this flag.
export const TRIP_UI: Record<string, Record<Lang, string>> = {
  'Active ride restored': { en: 'Active ride restored', fr: 'Trajet actif restauré', rw: 'Urugendo rukiriho rwagarutse' },
  'Dismiss': { en: 'Dismiss', fr: 'Fermer', rw: 'Funga' },
  'Back from navigation': { en: 'Back from navigation', fr: 'Retour de la navigation', rw: 'Wagarutse uvuye mu nzira' },
  'Ready to continue?': { en: 'Ready to continue?', fr: 'Prêt à continuer?', rw: 'Witeguye gukomeza?' },
  'Pickup': { en: 'Pickup', fr: 'Point de ramassage', rw: 'Aho guterura' },
  'Destination': { en: 'Destination', fr: 'Destination', rw: 'Aho ugiye' },
  'Passenger': { en: 'Passenger', fr: 'Passager', rw: 'Umugenzi' },
  'Get Directions': { en: 'Get Directions', fr: 'Obtenir l\'itinéraire', rw: 'Reba inzira' },
  'Cancel this ride': { en: 'Cancel this ride', fr: 'Annuler ce trajet', rw: 'Kuraho uru rugendo' },
  'Cancel this ride?': { en: 'Cancel this ride?', fr: 'Annuler ce trajet?', rw: 'Kuraho uru rugendo?' },
  'Call passenger': { en: 'Call passenger', fr: 'Appeler le passager', rw: 'Hamagara umugenzi' },
  'Free Call': { en: 'Free Call', fr: 'Appel gratuit', rw: 'Guhamagara ku buntu' },
  'Through Zana — no airtime used': { en: 'Through Zana — no airtime used', fr: 'Via Zana — aucun crédit utilisé', rw: 'Binyuze kuri Zana — nta ma inite akoreshwa' },
  'Call Directly': { en: 'Call Directly', fr: 'Appeler directement', rw: 'Hamagara mu buryo butaziguye' },
  "Using your phone's carrier network": { en: "Using your phone's carrier network", fr: 'Via le réseau de votre opérateur', rw: 'Ukoresheje network ya telefoni yawe' },
  'Tell us why — this goes to the customer and to Zana.': { en: 'Tell us why — this goes to the customer and to Zana.', fr: 'Dites-nous pourquoi — ceci sera envoyé au client et à Zana.', rw: 'Tubwire impamvu — ibi bizajya ku mukiriya no kuri Zana.' },
  'Cancelling…': { en: 'Cancelling…', fr: 'Annulation…', rw: 'Birimo gukurwaho…' },
  'Confirm cancellation': { en: 'Confirm cancellation', fr: 'Confirmer l\'annulation', rw: 'Emeza gukuraho' },
  '⭐ Rate this passenger': { en: '⭐ Rate this passenger', fr: '⭐ Évaluer ce passager', rw: '⭐ Tanga amanota kuri uyu mugenzi' },
  'Ride cancelled': { en: 'Ride cancelled', fr: 'Trajet annulé', rw: 'Urugendo rwahagaritswe' },
  'Back to home': { en: 'Back to home', fr: 'Retour à l\'accueil', rw: 'Subira ahabanza' },
  'Collect payment': { en: 'Collect payment', fr: 'Percevoir le paiement', rw: 'Akira ubwishyu' },
  "Customer's MoMo number": { en: "Customer's MoMo number", fr: 'Numéro Mobile Money du client', rw: 'Numero ya MoMo y\'umukiriya' },
  'Send prompt again': { en: 'Send prompt again', fr: 'Renvoyer la demande', rw: 'Ohereza ubutumwa nanone' },
  'Send payment request': { en: 'Send payment request', fr: 'Envoyer la demande de paiement', rw: 'Ohereza icyifuzo cy\'ubwishyu' },
  'Collect cash instead': { en: 'Collect cash instead', fr: 'Percevoir en espèces', rw: 'Akira amafaranga y\'ikiganza' },
  'Recording cash payment…': { en: 'Recording cash payment…', fr: 'Enregistrement du paiement…', rw: 'Birimo kwandika ubwishyu…' },
  'Sending request...': { en: 'Sending request...', fr: 'Envoi en cours...', rw: 'Birimo koherezwa...' },
  'Waiting for payment': { en: 'Waiting for payment', fr: 'En attente du paiement', rw: 'Bitegereje ubwishyu' },
  'A prompt was sent to': { en: 'A prompt was sent to', fr: 'Une demande a été envoyée à', rw: 'Ubutumwa bwoherejwe kuri' },
  "Ask the customer to enter their PIN": { en: "Ask the customer to enter their PIN", fr: 'Demandez au client de saisir son code PIN', rw: 'Saba umukiriya kwandika PIN ye' },
  'Use a different number': { en: 'Use a different number', fr: 'Utiliser un autre numéro', rw: 'Koresha indi numero' },
  'Payment received': { en: 'Payment received', fr: 'Paiement reçu', rw: 'Ubwishyu bwakiriwe' },
  'Trip complete': { en: 'Trip complete', fr: 'Trajet terminé', rw: 'Urugendo rurangiye' },
  'Incoming call': { en: 'Incoming call', fr: 'Appel entrant', rw: 'Guhamagarwa' },
  'Zana Ride · Free Call': { en: 'Zana Ride · Free Call', fr: 'Zana Ride · Appel gratuit', rw: 'Zana Ride · Guhamagara ku buntu' },
  'Loading trip…': { en: 'Loading trip…', fr: 'Chargement du trajet…', rw: 'Birimo gupakira urugendo…' },
  'Could not cancel. Try again.': { en: 'Could not cancel. Try again.', fr: 'Impossible d\'annuler. Réessayez.', rw: 'Ntibyashobotse gukuraho. Ongera ugerageze.' },
  'This ride was already paid via MoMo — no need to collect cash.': { en: 'This ride was already paid via MoMo — no need to collect cash.', fr: 'Ce trajet a déjà été payé via Mobile Money — pas besoin de percevoir en espèces.', rw: 'Uru rugendo rwarishywe binyuze kuri MoMo — nta bwishyu bw\'ikiganza bukenewe.' },
  'Could not switch to cash. Please try again.': { en: 'Could not switch to cash. Please try again.', fr: 'Impossible de passer en espèces. Réessayez.', rw: 'Ntibyashobotse guhindukira ku bwishyu bw\'ikiganza. Ongera ugerageze.' },
  'Payment not confirmed. Ask the customer to check their phone.': { en: 'Payment not confirmed. Ask the customer to check their phone.', fr: 'Paiement non confirmé. Demandez au client de vérifier son téléphone.', rw: 'Ubwishyu ntibwemejwe. Saba umukiriya areba kuri telefoni ye.' },
  'Could not send the payment request': { en: 'Could not send the payment request', fr: 'Impossible d\'envoyer la demande de paiement', rw: 'Ntibyashobotse kohereza icyifuzo cy\'ubwishyu' },
  'Send a Mobile Money request for': { en: 'Send a Mobile Money request for', fr: 'Envoyer une demande Mobile Money pour', rw: 'Ohereza icyifuzo cya Mobile Money kuri' },
};

export function tt(key: string, lang: Lang): string {
  return TRIP_UI[key]?.[lang] ?? key;
}

