'use client';

export type Lang = 'en' | 'fr' | 'rw';

const STORAGE_KEY = 'zana_lang';

function accountStorageKey(accountToken?: string | null): string {
  if (!accountToken) return STORAGE_KEY;
  let hash = 2166136261;
  for (let i = 0; i < accountToken.length; i += 1) {
    hash ^= accountToken.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return STORAGE_KEY + ':' + (hash >>> 0).toString(16);
}

export const LANG_LABELS: Record<Lang, string> = {
  en: 'English',
  fr: 'Français',
  rw: 'Ikinyarwanda',
};

export function getStoredLang(accountToken?: string | null): Lang {
  if (typeof window === 'undefined') return 'en';

  const key = accountStorageKey(accountToken);
  const stored = localStorage.getItem(key);
  const legacyStored = stored ? null : localStorage.getItem(STORAGE_KEY);
  const saved = stored ?? legacyStored;
  if (saved === 'en' || saved === 'fr' || saved === 'rw') {
    if (!stored && accountToken) localStorage.setItem(key, saved);
    return saved;
  }

  // First visit: use the browser/device language when ZANA supports it.
  // English is the safe fallback for all other languages.
  const browserLanguages = navigator.languages?.length
    ? navigator.languages
    : [navigator.language];

  const detected: Lang =
    browserLanguages.some((value) => value.toLowerCase().startsWith('rw'))
      ? 'rw'
      : browserLanguages.some((value) => value.toLowerCase().startsWith('fr'))
        ? 'fr'
        : 'en';

  localStorage.setItem(key, detected);
  return detected;
}

export function setStoredLang(lang: Lang, accountToken?: string | null) {
  if (typeof window === 'undefined') return;
  localStorage.setItem(accountStorageKey(accountToken), lang);
}

// UI strings for the customer app in all three languages.
export const UI: Record<string, Record<Lang, string>> = {
  'What do you need today?': { en: 'What do you need today?', fr: 'Que voulez-vous aujourd\'hui?', rw: 'Ukeneye iki uyu munsi?' },
  'Wallet Balance': { en: 'Wallet Balance', fr: 'Solde du portefeuille', rw: 'Amafaranga afite' },
  'Top Up': { en: 'Top Up', fr: 'Recharger', rw: 'Shyiramo amafaranga' },
  'Send My Location': { en: 'Send My Location', fr: 'Envoyer ma localisation', rw: 'Ohereza aho ndi' },
  'Share a code instead of explaining your address': { en: 'Share a code instead of explaining your address', fr: 'Partagez un code au lieu d\'expliquer votre adresse', rw: 'Ohereza kode aho gusobanura aho uri' },
  'Orders': { en: 'Orders', fr: 'Commandes', rw: 'Ibyagurijwe' },
  'Wallet': { en: 'Wallet', fr: 'Portefeuille', rw: 'Amafaranga' },
  'Profile': { en: 'Profile', fr: 'Profil', rw: 'Umwirondoro' },
  'Home': { en: 'Home', fr: 'Accueil', rw: 'Ahabanza' },
  'Chat': { en: 'Chat', fr: 'Discussion', rw: 'Ganira' },
  'Send': { en: 'Send', fr: 'Envoyer', rw: 'Ohereza' },
  'Type a message…': { en: 'Type a message…', fr: 'Écrivez un message…', rw: 'Andika ubutumwa…' },
  'Language': { en: 'Language', fr: 'Langue', rw: 'Ururimi' },
  'Finding your driver…': { en: 'Finding your driver…', fr: 'Turimo gushaka umushoferi wawe…', rw: 'Turimo gushaka umushoferi wawe…' },
  'Driver assigned': { en: 'Driver assigned', fr: 'Chauffeur attribué', rw: 'Umushoferi yahawe urugendo' },
  'Driver is on the way': { en: 'Driver is on the way', fr: 'Umushoferi ari mu nzira', rw: 'Umushoferi ari mu nzira' },
  'Your driver has arrived': { en: 'Your driver has arrived', fr: 'Votre chauffeur est arrivé', rw: 'Umushoferi wawe yageze' },
  'On the way to your destination': { en: 'On the way to your destination', fr: 'Mu nzira igana aho ugiye', rw: 'Mu nzira igana aho ugiye' },
  'Trip completed': { en: 'Trip completed', fr: 'Urugendo rwarangiye', rw: 'Urugendo rwarangiye' },
  'No drivers available nearby': { en: 'No drivers available nearby', fr: 'Aucun chauffeur disponible à proximité', rw: 'Nta mushoferi uboneka hafi' },
  'Trip cancelled': { en: 'Trip cancelled', fr: 'Urugendo rwahagaritswe', rw: 'Urugendo rwahagaritswe' },
  'Your driver': { en: 'Your driver', fr: 'Umushoferi wawe', rw: 'Umushoferi wawe' },
  'rides': { en: 'rides', fr: 'ingendo', rw: 'ingendo' },
  'Check before you get in': { en: 'Check before you get in', fr: 'Reba mbere yo kwinjira', rw: 'Reba mbere yo kwinjira' },
  'Confirm this plate matches the car in front of you.': { en: 'Confirm this plate matches the car in front of you.', fr: 'Emeza ko iyi pulaka ihuye n\'imodoka iri imbere yawe.', rw: 'Emeza ko iyi pulaka ihuye n\'imodoka iri imbere yawe.' },
  'Driver is following the recommended route': { en: 'Driver is following the recommended route', fr: 'Umushoferi akurikira inzira yasabwe', rw: 'Umushoferi akurikira inzira yasabwe' },
  'motos': { en: 'motos', fr: 'amamoto', rw: 'amamoto' },
  'All trips completed': { en: 'All trips completed', fr: 'Ingendo zose zarangiye', rw: 'Ingendo zose zarangiye' },
  'to your pickup': { en: 'to your pickup', fr: 'ngo agere aho uri', rw: 'ngo agere aho uri' },
  'remaining': { en: 'remaining', fr: 'bisigaye', rw: 'bisigaye' },
  'Calculating ETA…': { en: 'Calculating ETA…', fr: 'Turimo kubara igihe agera…', rw: 'Turimo kubara igihe agera…' },
  'Shake your phone anytime to report a safety concern.': { en: 'Shake your phone anytime to report a safety concern.', fr: 'Nyeganyeza telefoni yawe igihe icyo ari cyo cyose kugira ngo utange ikibazo cy\'umutekano.', rw: 'Nyeganyeza telefoni yawe igihe icyo ari cyo cyose kugira ngo utange ikibazo cy\'umutekano.' },
  'Rate your ride': { en: 'Rate your ride', fr: 'Tanga amanota ku rugendo rwawe', rw: 'Tanga amanota ku rugendo rwawe' },
  'Report a problem': { en: 'Report a problem', fr: 'Tanga ikibazo', rw: 'Tanga ikibazo' },
  'Cancel Ride': { en: 'Cancel Ride', fr: 'Hagarika urugendo', rw: 'Hagarika urugendo' },
  'This ride has already started — report a problem instead.': { en: 'This ride has already started — report a problem instead.', fr: 'Uru rugendo rwatangiye — tanga ikibazo aho kubihagarika.', rw: 'Uru rugendo rwatangiye — tanga ikibazo aho kubihagarika.' },
  'Could not cancel. Try again.': { en: 'Could not cancel. Try again.', fr: 'Ntibyashobotse guhagarika. Ongera ugerageze.', rw: 'Ntibyashobotse guhagarika. Ongera ugerageze.' },
  'Could not join the call. Try calling again.': { en: 'Could not join the call. Try calling again.', fr: 'Ntibyashobotse kwinjira mu kuvugana. Ongera uhamagare.', rw: 'Ntibyashobotse kwinjira mu kuvugana. Ongera uhamagare.' },
  'Your driver cancelled this ride': { en: 'Your driver cancelled this ride', fr: 'Umushoferi wawe yahagaritse uru rugendo', rw: 'Umushoferi wawe yahagaritse uru rugendo' },
  'Incoming call': { en: 'Incoming call', fr: 'Uhamagawe', rw: 'Uhamagawe' },
  'Your driver is calling': { en: 'Your driver is calling', fr: 'Umushoferi wawe arakuhamagara', rw: 'Umushoferi wawe arakuhamagara' },
  'is calling': { en: 'is calling', fr: 'arakuhamagara', rw: 'arakuhamagara' },
  'Ride cancelled': { en: 'Ride cancelled', fr: 'Urugendo rwahagaritswe', rw: 'Urugendo rwahagaritswe' },
  'Book another ride': { en: 'Book another ride', fr: 'Fata urundi rugendo', rw: 'Fata urundi rugendo' },
  'your driver': { en: 'your driver', fr: 'umushoferi wawe', rw: 'umushoferi wawe' },
  'Driver': { en: 'Driver', fr: 'Chauffeur', rw: 'Umushoferi' },
  'Ride History': { en: 'Ride History', fr: 'Amateka y\'ingendo', rw: 'Amateka y\'ingendo' },
  'Total spent on rides': { en: 'Total spent on rides', fr: 'Amafaranga yose yakoreshejwe ku ngendo', rw: 'Amafaranga yose yakoreshejwe ku ngendo' },
  'Spent in': { en: 'Spent in', fr: 'Yakoreshejwe muri', rw: 'Yakoreshejwe muri' },
  'Total rides': { en: 'Total rides', fr: 'Ingendo zose', rw: 'Ingendo zose' },
  'Rides': { en: 'Rides', fr: 'Ingendo', rw: 'Ingendo' },
  'All time': { en: 'All time', fr: 'Igihe cyose', rw: 'Igihe cyose' },
  'No rides yet': { en: 'No rides yet', fr: 'Nta rugendo urahagira', rw: 'Nta rugendo urahagira' },
  'No rides in': { en: 'No rides in', fr: 'Nta rugendo muri', rw: 'Nta rugendo muri' },
  'No driver': { en: 'No driver', fr: 'Nta mushoferi', rw: 'Nta mushoferi' },
  'Completed': { en: 'Completed', fr: 'Byarangiye', rw: 'Byarangiye' },
  'Cancelled': { en: 'Cancelled', fr: 'Byahagaritswe', rw: 'Byahagaritswe' },
  'Driver cancelled': { en: 'Driver cancelled', fr: 'Umushoferi yahagaritse', rw: 'Umushoferi yahagaritse' },
  'Available balance': { en: 'Available balance', fr: 'Amafaranga uri kubona', rw: 'Amafaranga uri kubona' },
  'Recent transactions': { en: 'Recent transactions', fr: 'Ibikorwa vuba aha', rw: 'Ibikorwa vuba aha' },
  'No transactions yet.': { en: 'No transactions yet.', fr: 'Nta bikorwa birabaho.', rw: 'Nta bikorwa birabaho.' },
  'Top up': { en: 'Top up', fr: 'Kongeraho', rw: 'Kongeraho' },
  'Payment': { en: 'Payment', fr: 'Ubwishyu', rw: 'Ubwishyu' },
  'Ride recorded': { en: 'Ride recorded', fr: 'Urugendo rwanditswe', rw: 'Urugendo rwanditswe' },
  'Pending': { en: 'Pending', fr: 'Bitegereje', rw: 'Bitegereje' },
  'No charge': { en: 'No charge', fr: 'Nta kiguzi', rw: 'Nta kiguzi' },
  'Bal:': { en: 'Bal:', fr: 'Amasigaye:', rw: 'Amasigaye:' },
  'Top up with Mobile Money': { en: 'Top up with Mobile Money', fr: 'Ongeraho ukoresheje Mobile Money', rw: 'Ongeraho ukoresheje Mobile Money' },
  'Mobile money number': { en: 'Mobile money number', fr: 'Numero ya Mobile Money', rw: 'Numero ya Mobile Money' },
  'Amount (RWF)': { en: 'Amount (RWF)', fr: 'Amafaranga (RWF)', rw: 'Amafaranga (RWF)' },
  'Request payment': { en: 'Request payment', fr: 'Saba ubwishyu', rw: 'Saba ubwishyu' },
  'Check your phone': { en: 'Check your phone', fr: 'Reba kuri telefoni yawe', rw: 'Reba kuri telefoni yawe' },
  'Approve the': { en: 'Approve the', fr: 'Emeza', rw: 'Emeza' },
  'mobile money request sent to': { en: 'mobile money request sent to', fr: 'ubusabe bwa mobile money bwoherejwe kuri', rw: 'ubusabe bwa mobile money bwoherejwe kuri' },
  'Top-up successful': { en: 'Top-up successful', fr: 'Kongeraho byagenze neza', rw: 'Kongeraho byagenze neza' },
  'Your wallet has been credited.': { en: 'Your wallet has been credited.', fr: 'Amafaranga yawe yongewe.', rw: 'Amafaranga yawe yongewe.' },
  'Done': { en: 'Done', fr: 'Byarangiye', rw: 'Byarangiye' },
  'Payment failed or was declined': { en: 'Payment failed or was declined', fr: 'Ubwishyu bwanze cyangwa bwanzwe', rw: 'Ubwishyu bwanze cyangwa bwanzwe' },
  'Try again': { en: 'Try again', fr: 'Ongera ugerageze', rw: 'Ongera ugerageze' },
  'Could not reach the payment provider.': { en: 'Could not reach the payment provider.', fr: 'Ntibyashobotse guhuza n\'uwishyura.', rw: 'Ntibyashobotse guhuza n\'uwishyura.' },
  'Cash': { en: 'Cash', fr: 'Amafaranga', rw: 'Amafaranga' },
  'Zana Wallet': { en: 'Zana Wallet', fr: 'Amafaranga ya Zana', rw: 'Amafaranga ya Zana' },
  'Mobile Money': { en: 'Mobile Money', fr: 'Mobile Money', rw: 'Mobile Money' },
  'Trip completed ·': { en: 'Trip completed ·', fr: 'Urugendo rwarangiye ·', rw: 'Urugendo rwarangiye ·' },
  'Route': { en: 'Route', fr: 'Inzira', rw: 'Inzira' },
  'Pickup': { en: 'Pickup', fr: 'Gutora', rw: 'Gutora' },
  'Destination': { en: 'Destination', fr: 'Aho ugiye', rw: 'Aho ugiye' },
  'Fare breakdown': { en: 'Fare breakdown', fr: 'Ibisobanuro by\'ikiguzi', rw: 'Ibisobanuro by\'ikiguzi' },
  'Base fare': { en: 'Base fare', fr: 'Ikiguzi shingiro', rw: 'Ikiguzi shingiro' },
  'Total charged': { en: 'Total charged', fr: 'Byose byishyuwe', rw: 'Byose byishyuwe' },
  'Trip details': { en: 'Trip details', fr: 'Ibisobanuro by\'urugendo', rw: 'Ibisobanuro by\'urugendo' },
  'Date': { en: 'Date', fr: 'Itariki', rw: 'Itariki' },
  'Service type': { en: 'Service type', fr: 'Ubwoko bw\'umurimo', rw: 'Ubwoko bw\'umurimo' },
  'Trip ID': { en: 'Trip ID', fr: 'Nomero y\'urugendo', rw: 'Nomero y\'urugendo' },
  'Zana Points earned': { en: 'Zana Points earned', fr: 'Amanota ya Zana wabonye', rw: 'Amanota ya Zana wabonye' },
  'Points added to your account': { en: 'Points added to your account', fr: 'Amanota yongewe kuri konti yawe', rw: 'Amanota yongewe kuri konti yawe' },
  'Back to Home': { en: 'Back to Home', fr: 'Subira ahabanza', rw: 'Subira ahabanza' },
  'Finding courier': { en: 'Finding courier', fr: 'Gushaka umutwara', rw: 'Gushaka umutwara' },
  'Courier assigned': { en: 'Courier assigned', fr: 'Umutwara yahawe umurimo', rw: 'Umutwara yahawe umurimo' },
  'On the way': { en: 'On the way', fr: 'Ari mu nzira', rw: 'Ari mu nzira' },
  'Delivered': { en: 'Delivered', fr: 'Byatanzwe', rw: 'Byatanzwe' },
  'Confirmed': { en: 'Confirmed', fr: 'Byemejwe', rw: 'Byemejwe' },
  'Preparing': { en: 'Preparing', fr: 'Birategurwa', rw: 'Birategurwa' },
  'Ready for pickup': { en: 'Ready for pickup', fr: 'Biteguye gutorwa', rw: 'Biteguye gutorwa' },
  'My Activity': { en: 'My Activity', fr: 'Ibikorwa byanjye', rw: 'Ibikorwa byanjye' },
  'Deliveries': { en: 'Deliveries', fr: 'Ibyoherejwe', rw: 'Ibyoherejwe' },
  'No orders yet. Try Food or Gifts!': { en: 'No orders yet. Try Food or Gifts!', fr: 'Nta bicuruzwa urahagira. Gerageza Ibiryo cyangwa Impano!', rw: 'Nta bicuruzwa urahagira. Gerageza Ibiryo cyangwa Impano!' },
  'Your deliveries will show up here.': { en: 'Your deliveries will show up here.', fr: 'Ibicuruzwa byawe bizagaragara hano.', rw: 'Ibicuruzwa byawe bizagaragara hano.' },
  'How was this delivery?': { en: 'How was this delivery?', fr: 'Ese iki gicuruzwa cyagenze gite?', rw: 'Ese iki gicuruzwa cyagenze gite?' },
  'Rate this delivery': { en: 'Rate this delivery', fr: 'Tanga amanota kuri iki gicuruzwa', rw: 'Tanga amanota kuri iki gicuruzwa' },
  'Ride': { en: 'Ride', fr: 'Urugendo', rw: 'Urugendo' },
  'Affordable & safe': { en: 'Affordable & safe', fr: 'Abordable et sûr', rw: 'Ku giciro cyiza kandi bifite umutekano' },
  'Moto Ride': { en: 'Moto Ride', fr: 'Urugendo rwa Moto', rw: 'Urugendo rwa Moto' },
  'Fast & reliable': { en: 'Fast & reliable', fr: 'Rapide et fiable', rw: 'Byihuta kandi byizewe' },
  'Delivery': { en: 'Delivery', fr: 'Kohereza', rw: 'Kohereza' },
  'Send anything': { en: 'Send anything', fr: 'Ohereza icyo cyose', rw: 'Ohereza icyo cyose' },
  'Order Food': { en: 'Order Food', fr: 'Saba Ibiryo', rw: 'Saba Ibiryo' },
  'Meals & drinks': { en: 'Meals & drinks', fr: 'Ibiryo n\'ibinyobwa', rw: 'Ibiryo n\'ibinyobwa' },
  'Shop': { en: 'Shop', fr: 'Guhaha', rw: 'Guhaha' },
  'Groceries & goods': { en: 'Groceries & goods', fr: 'Ibiribwa n\'ibindi bicuruzwa', rw: 'Ibiribwa n\'ibindi bicuruzwa' },
  'Send Gift': { en: 'Send Gift', fr: 'Ohereza Impano', rw: 'Ohereza Impano' },
  'Roses & surprises': { en: 'Roses & surprises', fr: 'Amaroza n\'ibitunguranye', rw: 'Amaroza n\'ibitunguranye' },
  'Market': { en: 'Market', fr: 'Isoko', rw: 'Isoko' },
  'Agent shops for you': { en: 'Agent shops for you', fr: 'Umukozi arakuguriza', rw: 'Umukozi arakuguriza' },
  'All services': { en: 'All services', fr: 'Serivisi zose', rw: 'Serivisi zose' },
  'Photo of the item': { en: 'Photo of the item', fr: 'Photo de l’article', rw: 'Ifoto y’ikintu' },
  'Take a photo': { en: 'Take a photo', fr: 'Prendre une photo', rw: 'Fata ifoto' },
  'Opening camera…': { en: 'Opening camera…', fr: 'Ouverture de la caméra…', rw: 'Turafungura kamera…' },
  'or choose from your gallery': { en: 'or choose from your gallery', fr: 'ou choisissez dans votre galerie', rw: 'cyangwa uhitemo mu mafoto yawe' },
  'Pickup location': { en: 'Pickup location', fr: 'Lieu de prise en charge', rw: 'Aho ufatirwa' },
  'Drag the green pin on the map to adjust.': { en: 'Drag the green pin on the map to adjust.', fr: 'Déplacez le repère vert sur la carte pour ajuster.', rw: 'Kurura akamenyetso k’icyatsi ku ikarita kugira ngo uhindure aho ufatirwa.' },
  'Delivery location': { en: 'Delivery location', fr: 'Lieu de livraison', rw: 'Aho kugeza' },
  'Search for the delivery address': { en: 'Search for the delivery address', fr: 'Rechercher l’adresse de livraison', rw: 'Shakisha aho kugeza' },
  'Use code': { en: 'Use code', fr: 'Utiliser le code', rw: 'Koresha kode' },
  'Receiver can\'t explain their address? Ask them to send you their Zana location code.': { en: 'Receiver can\'t explain their address? Ask them to send you their Zana location code.', fr: 'Le destinataire ne peut pas expliquer son adresse ? Demandez-lui d’envoyer son code de localisation Zana.', rw: 'Uwo wohereza ntashobora gusobanura aho ari? Musabe akohereze kode y’aho ari ya Zana.' },
  'Receiver\'s name (optional)': { en: 'Receiver\'s name (optional)', fr: 'Nom du destinataire (facultatif)', rw: 'Izina ry’uwo wohereza (si ngombwa)' },
  'Delivery fee': { en: 'Delivery fee', fr: 'Frais de livraison', rw: 'Amafaranga yo kugeza' },
  'How will you pay?': { en: 'How will you pay?', fr: 'Comment allez-vous payer ?', rw: 'Uzarishyura ute?' },
  'Tap to view order details': { en: 'Tap to view order details', fr: 'Appuyez pour voir les détails de la commande', rw: 'Kanda urebe ibisobanuro by’itegeko' },
  'Order summary': { en: 'Order summary', fr: 'Résumé de la commande', rw: 'Incamake y’itegeko' },
  'Items': { en: 'Items', fr: 'Articles', rw: 'Ibicuruzwa' },
  'Total': { en: 'Total', fr: 'Total', rw: 'Byose hamwe' },
  'Delivery recipient': { en: 'Delivery recipient', fr: 'Destinataire de la livraison', rw: 'Uwo kugeza' },
  'RWF total': { en: 'RWF total', fr: 'Total en RWF', rw: 'Igiteranyo muri RWF' },
  'Ride Scheduled': { en: 'Ride Scheduled', fr: 'Course programmée', rw: 'Urugendo rwateguwe' },
  'Confirmed for': { en: 'Confirmed for', fr: 'Confirmée pour', rw: 'Byemejwe kuri' },
  'Schedule a Ride': { en: 'Schedule a Ride', fr: 'Programmer une course', rw: 'Teganya urugendo' },
  'Book up to 24 hours in advance': { en: 'Book up to 24 hours in advance', fr: 'Réservez jusqu’à 24 heures à l’avance', rw: 'Teganya kugera ku masaha 24 mbere' },
  'Where should we pick you up?': { en: 'Where should we pick you up?', fr: 'Oduza he?', rw: 'Tuzagufatira he?' },
  'Where are you going?': { en: 'Where are you going?', fr: 'Mujya he?', rw: 'Ugiye he?' },
  'Pickup time': { en: 'Pickup time', fr: 'Heure de prise en charge', rw: 'Igihe cyo gufatwa' },
  'Ride type': { en: 'Ride type', fr: 'Type de course', rw: 'Ubwoko bw’urugendo' },
  'Special request (optional)': { en: 'Special request (optional)', fr: 'Demande spéciale (facultatif)', rw: 'Icyifuzo cyihariye (si ngombwa)' },
  'Scheduling...': { en: 'Scheduling...', fr: 'Programmation...', rw: 'Turateganya...' },
  'Schedule Ride': { en: 'Schedule Ride', fr: 'Programmer la course', rw: 'Teganya urugendo' },
  'Shop & Deliver': { en: 'Shop & Deliver', fr: 'Acheter et faire livrer', rw: 'Gura kandi ugezweho' },
  'No shops available yet.': { en: 'No shops available yet.', fr: 'Aucun magasin disponible pour le moment.', rw: 'Nta maduka arahari ubu.' },
  'Food & Drinks': { en: 'Food & Drinks', fr: 'Nourriture et boissons', rw: 'Ibiribwa n’ibinyobwa' },
  'No restaurants available yet.': { en: 'No restaurants available yet.', fr: 'Aucun restaurant disponible pour le moment.', rw: 'Nta maresitora arahari ubu.' },
  'Please fill pickup, destination and time.': { en: 'Please fill pickup, destination and time.', fr: 'Veuillez renseigner le départ, la destination et l’heure.', rw: 'Uzuza aho ufatira, aho ujya n’igihe.' },
  'Could not schedule ride.': { en: 'Could not schedule ride.', fr: 'Impossible de programmer la course.', rw: 'Ntibyashobotse guteganya urugendo.' },
  'You will be notified 45 minutes before pickup. Your driver will be assigned automatically.': { en: 'You will be notified 45 minutes before pickup. Your driver will be assigned automatically.', fr: 'Vous serez informé 45 minutes avant la prise en charge. Votre chauffeur sera attribué automatiquement.', rw: 'Uzamenyeshwa iminota 45 mbere yo gufatwa. Umushoferi azahabwa urugendo mu buryo bwikora.' },
  'Airport Drop-off': { en: 'Airport Drop-off', fr: 'Dépose à l’aéroport', rw: 'Kujyana ku kibuga cy’indege' },
  'Airport Pick-up': { en: 'Airport Pick-up', fr: 'Prise en charge à l’aéroport', rw: 'Kwakirira ku kibuga cy’indege' },
  'Bank Visit': { en: 'Bank Visit', fr: 'Visite à la banque', rw: 'Kujya kuri banki' },
  'Hospital': { en: 'Hospital', fr: 'Hôpital', rw: 'Ibitaro' },
  'Hotel': { en: 'Hotel', fr: 'Hôtel', rw: 'Hoteli' },
  'Wedding': { en: 'Wedding', fr: 'Mariage', rw: 'Ubukwe' },
  'Shopping Trip': { en: 'Shopping Trip', fr: 'Course shopping', rw: 'Urugendo rwo guhaha' },
  'School Run': { en: 'School Run', fr: 'Trajet scolaire', rw: 'Kujyana ku ishuri' },
  'Custom': { en: 'Custom', fr: 'Personnalisé', rw: 'Ikindi' },
  'Fast & affordable': { en: 'Fast & affordable', fr: 'Rapide et abordable', rw: 'Byihuse kandi bihendutse' },
  'Up to 4 passengers': { en: 'Up to 4 passengers', fr: 'Jusqu’à 4 passagers', rw: 'Abagenzi bagera kuri 4' },
  'Top-rated drivers': { en: 'Top-rated drivers', fr: 'Chauffeurs très bien notés', rw: 'Abashoferi bafite amanota meza' },
  'Pay driver directly': { en: 'Pay driver directly', fr: 'Payer directement le chauffeur', rw: 'Ishyura umushoferi ako kanya' },
  'Deducted at trip end': { en: 'Deducted at trip end', fr: 'Déduit à la fin du trajet', rw: 'Bivanwamo urugendo rurangiye' },
  'MoMo request at trip end': { en: 'MoMo request at trip end', fr: 'Demande MoMo à la fin du trajet', rw: 'Ubusabe bwa MoMo urugendo rurangiye' },
  'Phone': { en: 'Phone', fr: 'Téléphone', rw: 'Telefone' },
  'Phone number cannot be changed.': { en: 'Phone number cannot be changed.', fr: 'Le numéro de téléphone ne peut pas être modifié.', rw: 'Numero ya telefone ntishobora guhindurwa.' },
  'Saved!': { en: 'Saved!', fr: 'Enregistré !', rw: 'Byabitswe!' },
  'Send my location': { en: 'Send my location', fr: 'Envoyer ma localisation', rw: 'Ohereza aho ndi' },
  'Your location code': { en: 'Your location code', fr: 'Votre code de localisation', rw: 'Kode y’aho uri' },
  'This code has expired': { en: 'This code has expired', fr: 'Ce code a expiré', rw: 'Iyi kode yarangiye' },
  'Check back soon.': { en: 'Check back soon.', fr: 'Revenez bientôt.', rw: 'Garuka vuba.' },
  'Could not load shops.': { en: 'Could not load shops.', fr: 'Impossible de charger les magasins.', rw: 'Ntibyashobotse gufungura amaduka.' },
  'Forgot your password?': { en: 'Forgot your password?', fr: 'Mot de passe oublié ?', rw: 'Wibagiwe ijambo ry’ibanga?' },
  'Enter your code': { en: 'Enter your code', fr: 'Entrez votre code', rw: 'Andika kode yawe' },
  'At least 6 characters': { en: 'At least 6 characters', fr: 'Au moins 6 caractères', rw: 'Nibura inyuguti 6' },
  'Sign in with a code': { en: 'Sign in with a code', fr: 'Se connecter avec un code', rw: 'Injira ukoresheje kode' },
  'Welcome back': { en: 'Welcome back', fr: 'Bon retour', rw: 'Murakaza neza' },
  'Log in with your email or phone number.': { en: 'Log in with your email or phone number.', fr: 'Connectez-vous avec votre e-mail ou votre numéro de téléphone.', rw: 'Injira ukoresheje imeyili cyangwa nimero ya telefone.' },
  'Email or phone number': { en: 'Email or phone number', fr: 'E-mail ou numéro de téléphone', rw: 'Imeyili cyangwa nimero ya telefone' },
  'Password': { en: 'Password', fr: 'Mot de passe', rw: 'Ijambo ry’ibanga' },
  'Create your profile': { en: 'Create your profile', fr: 'Créez votre profil', rw: 'Kora umwirondoro wawe' },
  'Just the basics for now.': { en: 'Just the basics for now.', fr: 'Pour commencer, juste l’essentiel.', rw: 'Kugeza ubu, amakuru y’ibanze gusa.' },
  'First name': { en: 'First name', fr: 'Prénom', rw: 'Izina' },
  'Last name': { en: 'Last name', fr: 'Nom', rw: 'Izina ry’umuryango' },
  'Create your account': { en: 'Create your account', fr: 'Créez votre compte', rw: 'Kora konti yawe' },
  'Just the basics to get you moving.': { en: 'Just the basics to get you moving.', fr: 'Juste l’essentiel pour commencer.', rw: 'Amakuru y’ibanze kugira ngo utangire.' },
  'Email address': { en: 'Email address', fr: 'Adresse e-mail', rw: 'Aderesi ya imeyili' },
  'Password (min. 6 characters)': { en: 'Password (min. 6 characters)', fr: 'Mot de passe (6 caractères min.)', rw: 'Ijambo ry’ibanga (inyuguti 6 nibura)' },

};


// Reviewed Rwanda-facing translations for the core customer dashboard.
Object.assign(UI, {
  'Wallet Balance': { en: 'Wallet Balance', fr: 'Solde du portefeuille', rw: 'Amafaranga asigaye mu gikapo' },
  'Top Up': { en: 'Top Up', fr: 'Recharger', rw: 'Ongeramo amafaranga' },
  'Orders': { en: 'Orders', fr: 'Commandes', rw: 'Amabwiriza' },
  'Home': { en: 'Home', fr: 'Accueil', rw: 'Ahabanza' },
  'Chat': { en: 'Chat', fr: 'Discussion', rw: 'Kuganira' },
  'Finding your driver…': { en: 'Finding your driver…', fr: 'Recherche de votre chauffeur…', rw: 'Turimo gushaka umushoferi wawe…' },
  'Driver assigned': { en: 'Driver assigned', fr: 'Chauffeur attribué', rw: 'Umushoferi yagenewe urugendo' },
  'Driver is on the way': { en: 'Driver is on the way', fr: 'Le chauffeur est en route', rw: 'Umushoferi ari mu nzira' },
  'Your driver has arrived': { en: 'Your driver has arrived', fr: 'Votre chauffeur est arrivé', rw: 'Umushoferi wawe yageze' },
  'Trip completed': { en: 'Trip completed', fr: 'Trajet terminé', rw: 'Urugendo rwarangiye' },
  'No drivers available nearby': { en: 'No drivers available nearby', fr: 'Aucun chauffeur disponible à proximité', rw: 'Nta mushoferi uri hafi uboneka' },
  'Trip cancelled': { en: 'Trip cancelled', fr: 'Trajet annulé', rw: 'Urugendo rwahagaritswe' },
  'Cancel Ride': { en: 'Cancel Ride', fr: 'Annuler le trajet', rw: 'Hagarika urugendo' },
  'Could not cancel. Try again.': { en: 'Could not cancel. Try again.', fr: 'Impossible d’annuler. Réessayez.', rw: 'Ntibyashobotse guhagarika. Ongera ugerageze.' },
  'Rate your ride': { en: 'Rate your ride', fr: 'Évaluez votre trajet', rw: 'Tanga amanota ku rugendo rwawe' },
  'Report a problem': { en: 'Report a problem', fr: 'Signaler un problème', rw: 'Tanga raporo y’ikibazo' },
  'Ride History': { en: 'Ride History', fr: 'Historique des trajets', rw: 'Amateka y’ingendo' },
  'Total spent on rides': { en: 'Total spent on rides', fr: 'Total dépensé pour les trajets', rw: 'Amafaranga yose yakoreshejwe mu ngendo' },
  'Total rides': { en: 'Total rides', fr: 'Nombre total de trajets', rw: 'Umubare w’ingendo zose' },
  'No rides yet': { en: 'No rides yet', fr: 'Aucun trajet pour le moment', rw: 'Nta rugendo uragira' },
  'Completed': { en: 'Completed', fr: 'Terminé', rw: 'Byarangiye' },
  'Cancelled': { en: 'Cancelled', fr: 'Annulé', rw: 'Byahagaritswe' },
  'Available balance': { en: 'Available balance', fr: 'Solde disponible', rw: 'Amafaranga ushobora gukoresha' },
  'Recent transactions': { en: 'Recent transactions', fr: 'Transactions récentes', rw: 'Ibikorwa biheruka' },
  'No transactions yet.': { en: 'No transactions yet.', fr: 'Aucune transaction pour le moment.', rw: 'Nta bikorwa birabaho.' },
  'Payment': { en: 'Payment', fr: 'Paiement', rw: 'Kwishyura' },
  'Pending': { en: 'Pending', fr: 'En attente', rw: 'Biracyategerejwe' },
  'Cash': { en: 'Cash', fr: 'Espèces', rw: 'Amafaranga y’inguzanyo y’amaboko' },
  'Mobile Money': { en: 'Mobile Money', fr: 'Mobile Money', rw: 'Mobile Money' },
  'Pickup': { en: 'Pickup', fr: 'Prise en charge', rw: 'Aho utorerwa' },
  'Destination': { en: 'Destination', fr: 'Destination', rw: 'Aho ugiye' },
  'Fare breakdown': { en: 'Fare breakdown', fr: 'Détail du tarif', rw: 'Ibisobanuro by’ikiguzi' },
  'Base fare': { en: 'Base fare', fr: 'Tarif de base', rw: 'Ikiguzi shingiro' },
  'Total charged': { en: 'Total charged', fr: 'Total facturé', rw: 'Amafaranga yose wishyuye' },
  'Trip details': { en: 'Trip details', fr: 'Détails du trajet', rw: 'Ibisobanuro by’urugendo' },
  'Date': { en: 'Date', fr: 'Date', rw: 'Itariki' },
  'Service type': { en: 'Service type', fr: 'Type de service', rw: 'Ubwoko bwa serivisi' },
  'Trip ID': { en: 'Trip ID', fr: 'ID du trajet', rw: 'Nomero y’urugendo' },
  'Back to Home': { en: 'Back to Home', fr: 'Retour à l’accueil', rw: 'Subira ahabanza' },
  'Delivery': { en: 'Delivery', fr: 'Livraison', rw: 'Kohereza' },
  'Order Food': { en: 'Order Food', fr: 'Commander à manger', rw: 'Gutegeka ibiryo' },
  'Shop': { en: 'Shop', fr: 'Boutique', rw: 'Guhaha' },
  'Send Gift': { en: 'Send Gift', fr: 'Envoyer un cadeau', rw: 'Ohereza impano' },
  'Market': { en: 'Market', fr: 'Marché', rw: 'Isoko' },
  'All services': { en: 'All services', fr: 'Tous les services', rw: 'Serivisi zose' },
});

Object.assign(UI, {
  'Account settings': { en: 'Account settings', fr: 'Paramètres du compte', rw: 'Igenamiterere rya konti' },
  'Saved places': { en: 'Saved places', fr: 'Lieux enregistrés', rw: 'Ahantu wabikiye' },
  'Ride history': { en: 'Ride history', fr: 'Historique des trajets', rw: 'Amateka y’ingendo' },
  'Zana Points': { en: 'Zana Points', fr: 'Points Zana', rw: 'Amanota ya Zana' },
  'Safety': { en: 'Safety', fr: 'Sécurité', rw: 'Umutekano' },
  'Help & support': { en: 'Help & support', fr: 'Aide et assistance', rw: 'Ubufasha na serivisi' },
  'Log out': { en: 'Log out', fr: 'Se déconnecter', rw: 'Sohoka' },
});

Object.assign(UI, {
  'Change language': { en: 'Change language', fr: 'Changer de langue', rw: 'Hindura ururimi' },
});

Object.assign(UI, {
  'Good morning,': { en: 'Good morning,', fr: 'Bonjour,', rw: 'Mwaramutse,' },
  'Good afternoon,': { en: 'Good afternoon,', fr: 'Bon après-midi,', rw: 'Mwiriwe,' },
  'Good evening,': { en: 'Good evening,', fr: 'Bonsoir,', rw: 'Mwiriwe neza,' },
  'Welcome': { en: 'Welcome', fr: 'Bienvenue', rw: 'Murakaza neza' },
  'Kigali, Rwanda': { en: 'Kigali, Rwanda', fr: 'Kigali, Rwanda', rw: 'Kigali, Rwanda' },
  "Couldn't load your info. Check your connection.": { en: "Couldn't load your info. Check your connection.", fr: 'Impossible de charger vos informations. Vérifiez votre connexion.', rw: 'Ntibyashobotse kubona amakuru yawe. Reba umurongo wa internet.' },
  'Retry': { en: 'Retry', fr: 'Réessayer', rw: 'Ongera ugerageze' },
  'Where to?': { en: 'Where to?', fr: 'Où allez-vous ?', rw: 'Ujya he?' },
  'Search destination': { en: 'Search destination', fr: 'Rechercher une destination', rw: 'Shaka aho ugiye' },
  'No trips yet': { en: 'No trips yet', fr: 'Aucun trajet pour le moment', rw: 'Nta rugendo uragira' },
  'Set location': { en: 'Set location', fr: 'Définir le lieu', rw: 'Shyiraho ahantu' },
  'Work': { en: 'Work', fr: 'Travail', rw: 'Akazi' },
  'Recent': { en: 'Recent', fr: 'Récent', rw: 'Aheruka' },
  'Services': { en: 'Services', fr: 'Services', rw: 'Serivisi' },
  'Send packages with': { en: 'Send packages with', fr: 'Envoyez vos colis avec', rw: 'Ohereza ibicuruzwa ukoresheje' },
  'Zana Delivery': { en: 'Zana Delivery', fr: 'Zana Delivery', rw: 'Zana Delivery' },
  'Fast · Safe · Affordable': { en: 'Fast · Safe · Affordable', fr: 'Rapide · Sûr · Abordable', rw: 'Byihuse · Biteye umutekano · Bihendutse' },
  'Book now': { en: 'Book now', fr: 'Réserver maintenant', rw: 'Tanga ubusabe ubu' },
  'Pay with your Zana Wallet': { en: 'Pay with your Zana Wallet', fr: 'Payez avec votre portefeuille Zana', rw: 'Ishyura ukoresheje Zana Wallet yawe' },
  'Lower fees than Mobile Money, and no waiting for a payment prompt.': { en: 'Lower fees than Mobile Money, and no waiting for a payment prompt.', fr: 'Frais moins élevés que Mobile Money, sans attendre une demande de paiement.', rw: 'Kwishyura bihendutse kurusha Mobile Money kandi ntutegereze ubusabe bwo kwishyura.' },
  'Schedule': { en: 'Schedule', fr: 'Planifier', rw: 'Teganya' },
  'Location': { en: 'Location', fr: 'Localisation', rw: 'Aho uri' },
  'Going to': { en: 'Going to', fr: 'Direction', rw: 'Ugiye kuri' },
  'Moto': { en: 'Moto', fr: 'Moto', rw: 'Moto' },
  'Fast & cheap': { en: 'Fast & cheap', fr: 'Rapide et économique', rw: 'Byihuse kandi bihendutse' },
});

export function t(key: string, lang: Lang): string {
  return UI[key]?.[lang] ?? key;
}


Object.assign(UI, {
  'Welcome': { en: 'Welcome', fr: 'Bienvenue', rw: 'Murakaza neza' },
  'Good morning,': { en: 'Good morning,', fr: 'Bonjour,', rw: 'Mwaramutse,' },
  'Good afternoon,': { en: 'Good afternoon,', fr: 'Bon après-midi,', rw: 'Mwiriwe,' },
  'Good evening,': { en: 'Good evening,', fr: 'Bonsoir,', rw: 'Mwiriwe neza,' },
  'Kigali, Rwanda': { en: 'Kigali, Rwanda', fr: 'Kigali, Rwanda', rw: 'Kigali, u Rwanda' },
  "Couldn't load your info. Check your connection.": { en: "Couldn't load your info. Check your connection.", fr: "Impossible de charger vos informations. Vérifiez votre connexion.", rw: "Ntitwashoboye kubona amakuru yawe. Reba umurongo wa interineti." },
  'Retry': { en: 'Retry', fr: 'Réessayer', rw: 'Ongera ugerageze' },
  'Where to?': { en: 'Where to?', fr: 'Où allez-vous ?', rw: 'Mujya he?' },
  'Search destination': { en: 'Search destination', fr: 'Rechercher une destination', rw: 'Shaka aho ugiye' },
  'No trips yet': { en: 'No trips yet', fr: 'Aucun trajet pour le moment', rw: 'Nta rugendo uragira' },
  'Set location': { en: 'Set location', fr: 'Définir le lieu', rw: 'Shyiraho aho uherereye' },
  'Services': { en: 'Services', fr: 'Services', rw: 'Serivisi' },
  'Send packages with': { en: 'Send packages with', fr: 'Envoyez des colis avec', rw: 'Ohereza amapaki ukoresheje' },
  'Zana Delivery': { en: 'Zana Delivery', fr: 'Zana Delivery', rw: 'Zana Delivery' },
  'Fast · Safe · Affordable': { en: 'Fast · Safe · Affordable', fr: 'Rapide · Sûr · Abordable', rw: 'Byihuta · Bitekanye · Ku giciro cyiza' },
  'Book now': { en: 'Book now', fr: 'Réserver', rw: 'Fata ubu' },
  'delivery': { en: 'delivery', fr: 'livraison', rw: 'kohereza' },
  'Pay with your Zana Wallet': { en: 'Pay with your Zana Wallet', fr: 'Payez avec votre portefeuille Zana', rw: 'Ishyura ukoresheje Zana Wallet' },
  'Lower fees than Mobile Money, and no waiting for a payment prompt.': { en: 'Lower fees than Mobile Money, and no waiting for a payment prompt.', fr: "Frais moins élevés que Mobile Money, sans attendre une demande de paiement.", rw: 'Ni amafaranga make ugereranyije na Mobile Money, kandi nta gutegereza ubutumwa bw’ubwishyu.' },
  'Schedule': { en: 'Schedule', fr: 'Planifier', rw: 'Teganya' },
  'Location': { en: 'Location', fr: 'Localisation', rw: 'Aho uherereye' },
  'Going to': { en: 'Going to', fr: 'Vers', rw: 'Ugiye kuri' },
  'Fast & cheap': { en: 'Fast & cheap', fr: 'Rapide et économique', rw: 'Byihuta kandi bihendutse' },
  'Car': { en: 'Car', fr: 'Voiture', rw: 'Imodoka' },
  'Comfortable': { en: 'Comfortable', fr: 'Confortable', rw: 'Byoroheye' },
  'Change this saved place': { en: 'Change this saved place', fr: 'Modifier ce lieu enregistré', rw: 'Hindura aha hantu wabikiye' },
  'Account Settings': { en: 'Account Settings', fr: 'Paramètres du compte', rw: 'Igenamiterere rya konti' },
  'Personal Info': { en: 'Personal Info', fr: 'Informations personnelles', rw: 'Amakuru bwite' },
  'First Name': { en: 'First Name', fr: 'Prénom', rw: 'Izina bwite' },
  'Last Name': { en: 'Last Name', fr: 'Nom', rw: 'Izina ry’umuryango' },
  'Email': { en: 'Email', fr: 'E-mail', rw: 'Imeyili' },
  'Save Changes': { en: 'Save Changes', fr: 'Enregistrer les modifications', rw: 'Bika impinduka' },
  'Saved': { en: 'Saved', fr: 'Enregistré', rw: 'Byabitswe' },
  'Could not save changes.': { en: 'Could not save changes.', fr: 'Impossible d’enregistrer les modifications.', rw: 'Ntibyashobotse kubika impinduka.' },
});

Object.assign(UI, {
  'Messages auto-translate · History clears after ride': { en: 'Messages auto-translate · History clears after ride', fr: 'Les messages sont traduits automatiquement · L’historique est effacé après le trajet', rw: 'Ubutumwa buhindurwa ururimi mu buryo bwikora · Amateka asibwa urugendo rurangiye' },
  'No messages yet. Say hello!': { en: 'No messages yet. Say hello!', fr: 'Aucun message pour le moment. Dites bonjour !', rw: 'Nta butumwa burabaho. Vuga uti muraho!' },
  'Thank you!': { en: 'Thank you!', fr: 'Merci !', rw: 'Murakoze!' },
  'How was your ride with': { en: 'How was your ride with', fr: 'Urugendo rwanyu na', rw: 'Urugendo rwanyu na' },
  '?': { en: '?', fr: '?', rw: '?' },
  'Add a comment (optional)': { en: 'Add a comment (optional)', fr: 'Ajouter un commentaire (facultatif)', rw: 'Ongeraho igitekerezo (ntibitegetswe)' },
  'Report sent': { en: 'Report sent', fr: 'Rapport envoyé', rw: 'Raporo yoherejwe' },
  'Report an issue': { en: 'Report an issue', fr: 'Signaler un problème', rw: 'Tanga raporo y’ikibazo' },
  "Is everything okay? Select what's happening.": { en: "Is everything okay? Select what's happening.", fr: 'Tout va bien ? Sélectionnez ce qui se passe.', rw: 'Byose ni amahoro? Hitamo ikibazo kiri kuba.' },
  'Tell us what happened': { en: 'Tell us what happened', fr: 'Dites-nous ce qui s’est passé', rw: 'Tubwire ibyabaye' },
  'Anything you want to add? (optional)': { en: 'Anything you want to add? (optional)', fr: 'Quelque chose à ajouter ? (facultatif)', rw: 'Hari icyo ushaka kongeraho? (ntibitegetswe)' },
  'Choose a ride': { en: 'Choose a ride', fr: 'Choisissez un trajet', rw: 'Hitamo urugendo' },
  'Payment method': { en: 'Payment method', fr: 'Mode de paiement', rw: 'Uburyo bwo kwishyura' },
  '💳 How will you pay?': { en: '💳 How will you pay?', fr: '💳 Comment allez-vous payer ?', rw: '💳 Ugiye kwishyura ute?' },
  'Insufficient wallet balance': { en: 'Insufficient wallet balance', fr: 'Solde du portefeuille insuffisant', rw: 'Amafaranga ari mu gikapo ntabwo ahagije' },
});

Object.assign(UI, {
  'Food': { en: 'Food', fr: 'Nourriture', rw: 'Ibiryo' },
  'Clothes': { en: 'Clothes', fr: 'Vêtements', rw: 'Imyenda' },
  'Documents': { en: 'Documents', fr: 'Documents', rw: 'Inyandiko' },
  'Package': { en: 'Package', fr: 'Colis', rw: 'Ipaki' },
  'Medicine': { en: 'Medicine', fr: 'Médicaments', rw: 'Imiti' },
  'Groceries': { en: 'Groceries', fr: 'Produits alimentaires', rw: 'Ibicuruzwa byo mu rugo' },
  'Gift': { en: 'Gift', fr: 'Cadeau', rw: 'Impano' },
  'Electronics': { en: 'Electronics', fr: 'Électronique', rw: 'Ibikoresho bya elegitoroniki' },
  'Shoes': { en: 'Shoes', fr: 'Chaussures', rw: 'Inkweto' },
  'Books': { en: 'Books', fr: 'Livres', rw: 'Ibitabo' },
  'Cosmetics': { en: 'Cosmetics', fr: 'Cosmétiques', rw: 'Amavuta n’ibikoresho by’ubwiza' },
  'Household': { en: 'Household', fr: 'Articles ménagers', rw: 'Ibikoresho byo mu rugo' },
  'Other': { en: 'Other', fr: 'Autre', rw: 'Ibindi' },
  'Current location': { en: 'Current location', fr: 'Position actuelle', rw: 'Aho uri ubu' },
  'Could not process that image.': { en: 'Could not process that image.', fr: 'Impossible de traiter cette image.', rw: 'Ntibyashobotse gutunganya iyo foto.' },
  'Could not take that photo. Try again.': { en: 'Could not take that photo. Try again.', fr: 'Impossible de prendre cette photo. Réessayez.', rw: 'Ntibyashobotse gufata iyo foto. Ongera ugerageze.' },
  'Could not check that code.': { en: 'Could not check that code.', fr: 'Impossible de vérifier ce code.', rw: 'Ntibyashobotse kugenzura iyo kode.' },
  'Shared location': { en: 'Shared location', fr: 'Position partagée', rw: 'Aho wasangijwe' },
  'Payment was not confirmed. The delivery was cancelled — you can try again.': { en: 'Payment was not confirmed. The delivery was cancelled — you can try again.', fr: 'Le paiement n’a pas été confirmé. La livraison a été annulée — vous pouvez réessayer.', rw: 'Ubwishyu ntabwo bwemejwe. Kohereza byahagaritswe — ushobora kongera kugerageza.' },
  'Not enough in your wallet. Balance {{balance}} RWF, delivery costs {{cost}} RWF.': { en: 'Not enough in your wallet. Balance {{balance}} RWF, delivery costs {{cost}} RWF.', fr: 'Solde insuffisant. Solde {{balance}} RWF, livraison {{cost}} RWF.', rw: 'Amafaranga yo mu gikapo ntabwo ahagije. Asigaye {{balance}} RWF, kohereza ni {{cost}} RWF.' },
  'Could not reach Mobile Money. Check the number and try again.': { en: 'Could not reach Mobile Money. Check the number and try again.', fr: 'Impossible de joindre Mobile Money. Vérifiez le numéro et réessayez.', rw: 'Ntibyashobotse kugera kuri Mobile Money. Reba nimero wongere ugerageze.' },
  'Could not create the delivery.': { en: 'Could not create the delivery.', fr: 'Impossible de créer la livraison.', rw: 'Ntibyashobotse gutangiza kohereza.' },
  'Send a package': { en: 'Send a package', fr: 'Envoyer un colis', rw: 'Ohereza ipaki' },
  'What are you sending?': { en: 'What are you sending?', fr: 'Ohereza iki?', rw: 'Urimo kohereza iki?' },
  'Additional details': { en: 'Additional details', fr: 'Détails supplémentaires', rw: 'Andi makuru' },
  'optional': { en: 'optional', fr: 'facultatif', rw: 'ntibitegetswe' },
  'e.g. 2 plates of food and 1 bottle of juice': { en: 'e.g. 2 plates of food and 1 bottle of juice', fr: 'ex. 2 assiettes de nourriture et 1 bouteille de jus', rw: 'urugero: amasahani 2 y’ibiryo n’icupa 1 ry’umutobe' },
  'Approximate weight': { en: 'Approximate weight', fr: 'Poids approximatif', rw: 'Uburemere bugereranyijwe' },
  'Receiver': { en: 'Receiver', fr: 'Destinataire', rw: 'Uwakira' },
  'Receiver name': { en: 'Receiver name', fr: 'Nom du destinataire', rw: 'Izina ry’uwakira' },
  'Phone number': { en: 'Phone number', fr: 'Numéro de téléphone', rw: 'Nimero ya telefoni' },
  'Wallet': { en: 'Wallet', fr: 'Portefeuille', rw: 'Igikapo' },
  'Mobile Money': { en: 'Mobile Money', fr: 'Mobile Money', rw: 'Mobile Money' },
  'Cash': { en: 'Cash', fr: 'Espèces', rw: 'Amafaranga mu ntoki' },
  'Approve the MoMo prompt on your phone…': { en: 'Approve the MoMo prompt on your phone…', fr: 'Validez la demande MoMo sur votre téléphone…', rw: 'Emeza ubusabe bwa MoMo kuri telefoni yawe…' },
  'Requesting…': { en: 'Requesting…', fr: 'Demande en cours…', rw: 'Gusaba birakomeje…' },
  'Request Delivery': { en: 'Request Delivery', fr: 'Demander une livraison', rw: 'Saba ko koherezwa' },
  'Finding the best route…': { en: 'Finding the best route…', fr: 'Recherche du meilleur itinéraire…', rw: 'Turimo gushaka inzira nziza…' },
  'Calculating your fare…': { en: 'Calculating your fare…', fr: 'Calcul du tarif…', rw: 'Turimo kubara igiciro…' },
  'Confirming with Zana…': { en: 'Confirming with Zana…', fr: 'Confirmation avec Zana…', rw: 'Turimo kwemeza na Zana…' },
});


Object.assign(UI, {
  'Minimum 100 points': { en: 'Minimum 100 points', fr: 'Minimum 100 points', rw: 'Nibura amanota 100' },
  'points redeemed for': { en: 'points redeemed for', fr: 'points échangés contre', rw: 'amanota yakoreshejwe kuri' },
  'Could not redeem points': { en: 'Could not redeem points', fr: 'Impossible d’échanger les points', rw: 'Ntibyashobotse gukoresha amanota' },
  'Your points balance': { en: 'Your points balance', fr: 'Votre solde de points', rw: 'Amanota ufite' },
  'How to earn points': { en: 'How to earn points', fr: 'Comment gagner des points', rw: 'Uko wabona amanota' },
  'Redeem points': { en: 'Redeem points', fr: 'Échanger des points', rw: 'Koresha amanota' },
  'Points to redeem': { en: 'Points to redeem', fr: 'Points à échanger', rw: 'Amanota yo gukoresha' },
  'Recent activity': { en: 'Recent activity', fr: 'Activité récente', rw: 'Ibikorwa bya vuba' },
  'Help & Support': { en: 'Help & Support', fr: 'Aide et assistance', rw: 'Ubufasha n’ubwunganizi' },
  'Still need help?': { en: 'Still need help?', fr: 'Besoin d’aide ?', rw: 'Uracyakeneye ubufasha?' },
  'WhatsApp Support': { en: 'WhatsApp Support', fr: 'Assistance WhatsApp', rw: 'Ubufasha kuri WhatsApp' },
  'Location is not available on this device.': { en: 'Location is not available on this device.', fr: 'La localisation n’est pas disponible sur cet appareil.', rw: 'Aho uri ntihaboneka kuri iki gikoresho.' },
  'Could not read your location. Allow location access and try again.': { en: 'Could not read your location. Allow location access and try again.', fr: 'Impossible de lire votre position. Autorisez l’accès à la localisation et réessayez.', rw: 'Ntibyashobotse kumenya aho uri. Emera ko igikoresho kibona aho uri wongere ugerageze.' },
  'Saved Places': { en: 'Saved Places', fr: 'Lieux enregistrés', rw: 'Ahantu wabikiye' },
  'No saved places yet.': { en: 'No saved places yet.', fr: 'Aucun lieu enregistré pour le moment.', rw: 'Nta hantu wabika kugeza ubu.' },
  'New saved place': { en: 'New saved place', fr: 'Nouveau lieu enregistré', rw: 'Bika ahantu hashya' },
  'or': { en: 'or', fr: 'ou', rw: 'cyangwa' },
  'Search address': { en: 'Search address', fr: 'Rechercher une adresse', rw: 'Shaka aderesi' },
  'Type an address...': { en: 'Type an address...', fr: 'Saisissez une adresse...', rw: 'Andika aderesi...' },
  'Cancel': { en: 'Cancel', fr: 'Annuler', rw: 'Hagarika' },
  'Safety': { en: 'Safety', fr: 'Sécurité', rw: 'Umutekano' },
  'Emergency Contact': { en: 'Emergency Contact', fr: 'Contact d’urgence', rw: 'Uwo wahamagara mu gihe cy’amage' },
  'Share your trip details with trusted contacts for added safety.': { en: 'Share your trip details with trusted contacts for added safety.', fr: 'Partagez les détails de votre trajet avec des contacts de confiance pour plus de sécurité.', rw: 'Sangiza abo wizera amakuru y’urugendo rwawe kugira ngo urusheho kugira umutekano.' },
  'SOS Feature': { en: 'SOS Feature', fr: 'Fonction SOS', rw: 'Serivisi ya SOS' },
  'During any active ride, shake your phone or tap the SOS button to report a safety concern. Our team will be alerted immediately.': { en: 'During any active ride, shake your phone or tap the SOS button to report a safety concern. Our team will be alerted immediately.', fr: 'Pendant tout trajet actif, secouez votre téléphone ou appuyez sur le bouton SOS pour signaler un problème de sécurité. Notre équipe sera alertée immédiatement.', rw: 'Mu rugendo urimo, nyeganyeza telefoni cyangwa ukande kuri SOS kugira ngo utange amakuru ku kibazo cy’umutekano. Itsinda ryacu rizahita ribimenyeshwa.' },
});

// Deployment heartbeat: keep the production Pages build tracking the latest main commit.
// Production sync marker: latest main source should be picked up by the next Pages build.
// Pages deployment sync: customer-web production build trigger.
// Localization syntax repair sync: deploy the latest verified main source.


Object.assign(UI, {
  'Buy from the market': { en: 'Buy from the market', fr: 'Acheter au marché', rw: 'Gura ku isoko' },
  'An agent shops for you and a rider brings it': { en: 'An agent shops for you and a rider brings it', fr: 'Un agent achète pour vous et un motard vous livre', rw: 'Umukozi arakugurira maze umumotari akakuzanira' },
  'No markets available yet': { en: 'No markets available yet', fr: 'Aucun marché disponible pour le moment', rw: 'Nta masoko arahari ubu' },
  'item': { en: 'item', fr: 'article', rw: 'ikintu' },
  'items': { en: 'items', fr: 'articles', rw: 'ibintu' },
  'listed today': { en: 'listed today', fr: 'répertoriés aujourd’hui', rw: 'byashyizwe ku rutonde uyu munsi' },
  'value': { en: 'value', fr: 'valeur', rw: 'agaciro' },
  'earned total': { en: 'earned total', fr: 'gagnés au total', rw: 'yose wabonye' },
  'Per ride': { en: 'Per ride', fr: 'Par trajet', rw: 'Kuri buri rugendo' },
  '1 point per 100 RWF spent': { en: '1 point per 100 RWF spent', fr: '1 point par 100 RWF dépensés', rw: 'Inota 1 kuri RWF 100 ukoresheje' },
  'Per delivery': { en: 'Per delivery', fr: 'Par livraison', rw: 'Kuri buri kohereza' },
  '1 point per 200 RWF spent': { en: '1 point per 200 RWF spent', fr: '1 point par 200 RWF dépensés', rw: 'Inota 1 kuri RWF 200 ukoresheje' },
  'Rate a driver': { en: 'Rate a driver', fr: 'Évaluer un chauffeur', rw: 'Tanga amanota ku mushoferi' },
  '+2 bonus points': { en: '+2 bonus points', fr: '+2 points bonus', rw: '+2 y’amanota y’inyongera' },
  'First ride ever': { en: 'First ride ever', fr: 'Premier trajet', rw: 'Urugendo rwa mbere' },
  '+5 bonus points': { en: '+5 bonus points', fr: '+5 points bonus', rw: '+5 y’amanota y’inyongera' },
  '100 points = 500 RWF wallet credit (min 100 points)': { en: '100 points = 500 RWF wallet credit (min 100 points)', fr: '100 points = 500 RWF de crédit portefeuille (minimum 100 points)', rw: 'Amanota 100 = RWF 500 mu gikapo (nibura amanota 100)' },
  'Redeem': { en: 'Redeem', fr: 'Échanger', rw: 'Koresha' },
  'Deliver to': { en: 'Deliver to', fr: 'Livrer à', rw: 'Kugeza kuri' },
  'Myself': { en: 'Myself', fr: 'Moi-même', rw: 'Njye ubwanjye' },
  'Someone else': { en: 'Someone else', fr: 'Quelqu’un d’autre', rw: 'Undi muntu' },
  'Recipient full name': { en: 'Recipient full name', fr: 'Nom complet du destinataire', rw: 'Amazina yose y’uwakira' },
  'Recipient phone number': { en: 'Recipient phone number', fr: 'Numéro du destinataire', rw: 'Nimero ya telefoni y’uwakira' },
  'Delivery address': { en: 'Delivery address', fr: 'Adresse de livraison', rw: 'Aderesi yo kugeza' },
  "Drag the pin to the recipient's exact location. The order sends these coordinates with the address.": { en: "Drag the pin to the recipient's exact location. The order sends these coordinates with the address.", fr: 'Déplacez le repère vers la position exacte du destinataire. La commande envoie ces coordonnées avec l’adresse.', rw: 'Kurura akamenyetso aho uwakira ari neza. Itegeko ryohereza aho hantu hamwe na aderesi.' },
  "Use this device's current location": { en: "Use this device's current location", fr: 'Utiliser la position actuelle de cet appareil', rw: 'Koresha aho iki gikoresho kiri ubu' },
  'Delivery note (optional)': { en: 'Delivery note (optional)', fr: 'Note de livraison (facultatif)', rw: 'Icyitonderwa cyo kugeza (si ngombwa)' },
  'The account holder pays. The recipient only receives the order.': { en: 'The account holder pays. The recipient only receives the order.', fr: 'Le titulaire du compte paie. Le destinataire reçoit seulement la commande.', rw: 'Nyir’konti ni we wishyura. Uwakira ni we gusa uhabwa ibyo watumije.' },
  'Your saved delivery location': { en: 'Your saved delivery location', fr: 'Votre lieu de livraison enregistré', rw: 'Aho wabitse ko ari ho kugeza' },
  'Waiting for the rider to start moving…': { en: 'Waiting for the rider to start moving…', fr: 'En attente du départ du livreur…', rw: 'Turategereje ko umutwara atangira kugenda…' },
  'On the way to you': { en: 'On the way to you', fr: 'En route vers vous', rw: 'Ari mu nzira akugana' },
  'Collecting your parcel': { en: 'Collecting your parcel', fr: 'Récupération de votre colis', rw: 'Arimo gufata ipaki yawe' },
  'Position last updated a while ago — the rider may have lost signal.': { en: 'Position last updated a while ago — the rider may have lost signal.', fr: 'Position mise à jour il y a un moment — le livreur a peut-être perdu le signal.', rw: 'Aho umutwara aheruka kuvugurura hashize igihe — ashobora kuba yatakaje umurongo.' },
  'Thanks for rating': { en: 'Thanks for rating', fr: 'Merci d’avoir évalué', rw: 'Murakoze gutanga amanota kuri' },
  'Submitting…': { en: 'Submitting…', fr: 'Envoi…', rw: 'Birimo koherezwa…' },
  'Submit Rating': { en: 'Submit Rating', fr: 'Envoyer la note', rw: 'Ohereza amanota' },
  'Skip': { en: 'Skip', fr: 'Passer', rw: 'Simbuka' },
});


Object.assign(UI, {
  'How do I cancel a ride?': { en: 'How do I cancel a ride?', fr: 'Comment annuler un trajet ?', rw: 'Nabahagarika nte urugendo?' },
  'Tap "Cancel Ride" on the tracking screen before your driver arrives.': { en: 'Tap "Cancel Ride" on the tracking screen before your driver arrives.', fr: 'Appuyez sur « Annuler le trajet » sur l’écran de suivi avant l’arrivée du chauffeur.', rw: 'Kanda kuri “Hagarika urugendo” kuri ecran yo gukurikirana mbere y’uko umushoferi agera.' },
  'How do I top up my wallet?': { en: 'How do I top up my wallet?', fr: 'Comment recharger mon portefeuille ?', rw: 'Nongeramo nte amafaranga mu gikapo?' },
  'Go to Wallet → Top Up, enter an amount and your MTN/Airtel number.': { en: 'Go to Wallet → Top Up, enter an amount and your MTN/Airtel number.', fr: 'Allez dans Portefeuille → Recharger, saisissez un montant et votre numéro MTN/Airtel.', rw: 'Jya kuri Amafaranga → Shyiramo amafaranga, wandike umubare n’inimero ya MTN/Airtel.' },
  'What is a Zana location code?': { en: 'What is a Zana location code?', fr: 'Qu’est-ce qu’un code de localisation Zana ?', rw: 'Kode y’aho uri ya Zana ni iki?' },
  'A short code (e.g. ZANA-8XK29) that represents your exact GPS location. Share it when you can\'t explain your address.': { en: 'A short code (e.g. ZANA-8XK29) that represents your exact GPS location. Share it when you can\'t explain your address.', fr: 'Un code court qui représente votre position GPS exacte. Partagez-le lorsque vous ne pouvez pas expliquer votre adresse.', rw: 'Ni kode ngufi igaragaza neza aho GPS yawe iri. Yisangize abandi igihe udashobora gusobanura aderesi yawe.' },
  'How do I track my delivery?': { en: 'How do I track my delivery?', fr: 'Comment suivre ma livraison ?', rw: 'Nakurikirana nte ibyo natumije?' },
  'Go to Orders → Deliveries to see real-time status of all your packages.': { en: 'Go to Orders → Deliveries to see real-time status of all your packages.', fr: 'Allez dans Commandes → Livraisons pour voir le statut en temps réel de vos colis.', rw: 'Jya kuri Ibyagurijwe → Ibyoherejwe urebe uko amapaki yawe ahagaze ubu.' },
  'How does the fare work?': { en: 'How does the fare work?', fr: 'Comment fonctionne le tarif ?', rw: 'Igiciro cy’urugendo gitegurwa gite?' },
  'Fares are calculated by distance and time. You see the estimate before booking.': { en: 'Fares are calculated by distance and time. You see the estimate before booking.', fr: 'Les tarifs sont calculés selon la distance et le temps. Vous voyez l’estimation avant de réserver.', rw: 'Ibiciro bibarwa hashingiwe ku ntera n’igihe. Ubona ikigereranyo mbere yo gutanga ubusabe.' },
});


Object.assign(UI, {
  'Basic Car': { en: 'Basic Car', fr: 'Voiture standard', rw: 'Imodoka isanzwe' },
  'Comfortable · up to 4': { en: 'Comfortable · up to 4', fr: 'Confortable · jusqu’à 4', rw: 'Yoroheye · abantu bagera kuri 4' },
  'Premium Car': { en: 'Premium Car', fr: 'Voiture premium', rw: 'Imodoka nziza cyane' },
  'Top-rated drivers · up to 4': { en: 'Top-rated drivers · up to 4', fr: 'Chauffeurs très bien notés · jusqu’à 4', rw: 'Abashoferi bafite amanota meza · abantu bagera kuri 4' },
  'Pay the driver directly': { en: 'Pay the driver directly', fr: 'Payez directement le chauffeur', rw: 'Ishyura umushoferi ako kanya' },
  'Deducted at trip end': { en: 'Deducted at trip end', fr: 'Déduit à la fin du trajet', rw: 'Bikurwa urugendo rurangiye' },
  'MoMo request at trip end': { en: 'MoMo request at trip end', fr: 'Demande MoMo à la fin du trajet', rw: 'Ubusabe bwa MoMo ku musozo w’urugendo' },
  'Balance:': { en: 'Balance:', fr: 'Solde :', rw: 'Amafaranga asigaye:' },
  'need': { en: 'need', fr: 'besoin de', rw: 'ukeneye' },
  'more': { en: 'more', fr: 'de plus', rw: 'andi' },
  'Paying from your Zana Wallet costs less in fees and skips the payment prompt.': { en: 'Paying from your Zana Wallet costs less in fees and skips the payment prompt.', fr: 'Payer avec votre portefeuille Zana coûte moins cher et évite la demande de paiement.', rw: 'Kwishyura ukoresheje Zana Wallet bigabanya amafaranga y’ubwishyu kandi ntutegereze ubusabe.' },
  'Fare is calculated by distance and vehicle type.': { en: 'Fare is calculated by distance and vehicle type.', fr: 'Le tarif est calculé selon la distance et le type de véhicule.', rw: 'Igiciro kibazwa hakurikijwe intera n’ubwoko bw’imodoka.' },
  'Finding your driver...': { en: 'Finding your driver...', fr: 'Recherche de votre chauffeur...', rw: 'Turimo gushaka umushoferi wawe...' },
  'Confirm': { en: 'Confirm', fr: 'Confirmer', rw: 'Emeza' },
  'Change ride type': { en: 'Change ride type', fr: 'Changer de type de trajet', rw: 'Hindura ubwoko bw’urugendo' },
  'Could not reach the server.': { en: 'Could not reach the server.', fr: 'Impossible de joindre le serveur.', rw: 'Ntibyashobotse kugera kuri seriveri.' },
});


Object.assign(UI, {
  'Drag the green pin to adjust pickup': { en: 'Drag the green pin to adjust pickup', fr: 'Déplacez le repère vert pour ajuster le départ', rw: 'Kurura akamenyetso k’icyatsi uhindure aho ufatira' },
  'Search pickup location': { en: 'Search pickup location', fr: 'Rechercher le lieu de prise en charge', rw: 'Shaka aho ufatira' },
  'How many motos?': { en: 'How many motos?', fr: 'Combien de motos ?', rw: 'Amamoto angahe?' },
  'Booking': { en: 'Booking', fr: 'Réservation de', rw: 'Guteganya' },
  'Booking your moto…': { en: 'Booking your moto…', fr: 'Réservation de votre moto…', rw: 'Turimo guteganya moto yawe…' },
  'moto': { en: 'moto', fr: 'moto', rw: 'moto' },
  'car': { en: 'car', fr: 'voiture', rw: 'imodoka' },
  's': { en: 's', fr: 's', rw: '' },
  'available nearby': { en: 'available nearby', fr: 'disponibles à proximité', rw: 'ziboneka hafi' },
  'Searching…': { en: 'Searching…', fr: 'Recherche…', rw: 'Turashakisha…' },
  'Receiver shared a Zana location code? Enter it as your destination.': { en: 'Receiver shared a Zana location code? Enter it as your destination.', fr: 'Le destinataire a partagé un code de localisation Zana ? Saisissez-le comme destination.', rw: 'Uwo wohereje yasangiye kode y’aho ari ya Zana? Yandike nk’aho ujya.' },
  'Use': { en: 'Use', fr: 'Utiliser', rw: 'Koresha' },
  'No matching places.': { en: 'No matching places.', fr: 'Aucun lieu correspondant.', rw: 'Nta hantu hahuye habonetse.' },
  'How will you pay?': { en: 'How will you pay?', fr: 'Comment allez-vous payer ?', rw: 'Ugiye kwishyura ute?' },
  'seats': { en: 'seats', fr: 'places', rw: 'imyanya' },
  'seat': { en: 'seat', fr: 'place', rw: 'umwanya' },
  'Moto ride': { en: 'Moto ride', fr: 'Trajet en moto', rw: 'Urugendo rwa moto' },
  'Calculating...': { en: 'Calculating...', fr: 'Calcul en cours...', rw: 'Turimo kubara...' },
  'Insufficient balance.': { en: 'Insufficient balance.', fr: 'Solde insuffisant.', rw: 'Amafaranga asigaye ntabwo ahagije.' },
  'Your wallet has': { en: 'Your wallet has', fr: 'Votre portefeuille contient', rw: 'Igikapo cyawe gifite' },
  'Choose another payment method or top up.': { en: 'Choose another payment method or top up.', fr: 'Choisissez un autre mode de paiement ou rechargez.', rw: 'Hitamo ubundi buryo bwo kwishyura cyangwa wongere amafaranga.' },
  'Confirm & Book': { en: 'Confirm & Book', fr: 'Confirmer et réserver', rw: 'Emeza kandi uteganye' },
  'That code was not found or has expired.': { en: 'That code was not found or has expired.', fr: 'Ce code est introuvable ou a expiré.', rw: 'Iyo kode ntibonetse cyangwa yararangiye.' },
});


Object.assign(UI, {
  'A Zana agent buys these items for you at the market, then a rider delivers them.': { en: 'A Zana agent buys these items for you at the market, then a rider delivers them.', fr: 'Un agent Zana achète ces articles au marché pour vous, puis un motard vous les livre.', rw: 'Umukozi wa Zana akugurira ibi bintu ku isoko, maze umumotari akabikuzanira.' },
  'Nothing listed here today': { en: 'Nothing listed here today', fr: 'Rien de répertorié ici aujourd’hui', rw: 'Nta kintu cyashyizwe hano uyu munsi' },
  'Review': { en: 'Review', fr: 'Vérifier', rw: 'Reba' },
  'Confirm your order': { en: 'Confirm your order', fr: 'Confirmez votre commande', rw: 'Emeza ibyo watumije' },
  'Delivery (estimate)': { en: 'Delivery (estimate)', fr: 'Livraison (estimation)', rw: 'Kohereza (ikigereranyo)' },
  'Final delivery fee is calculated from the market to your location.': { en: 'Final delivery fee is calculated from the market to your location.', fr: 'Les frais finaux de livraison sont calculés du marché jusqu’à votre position.', rw: 'Amafaranga ya nyuma yo kugeza abarwa kuva ku isoko kugeza aho uri.' },
  'Wallet balance:': { en: 'Wallet balance:', fr: 'Solde du portefeuille :', rw: 'Amafaranga ari mu gikapo:' },
  'Placing order…': { en: 'Placing order…', fr: 'Commande en cours…', rw: 'Turimo gutanga itegeko…' },
  'Pay & Order': { en: 'Pay & Order', fr: 'Payer et commander', rw: 'Ishyura kandi utegeke' },
  'Could not place the order.': { en: 'Could not place the order.', fr: 'Impossible de passer la commande.', rw: 'Ntibyashobotse gutanga itegeko.' },
  'Add a place': { en: 'Add a place', fr: 'Ajouter un lieu', rw: 'Ongeraho ahantu' },
  'Finding you…': { en: 'Finding you…', fr: 'Recherche de votre position…', rw: 'Turimo kumenya aho uri…' },
  'Use my current location': { en: 'Use my current location', fr: 'Utiliser ma position actuelle', rw: 'Koresha aho ndi ubu' },
  'Saving...': { en: 'Saving...', fr: 'Enregistrement...', rw: 'Turabika...' },
  'Save': { en: 'Save', fr: 'Enregistrer', rw: 'Bika' },
  'Registered phone number': { en: 'Registered phone number', fr: 'Numéro de téléphone enregistré', rw: 'Nimero ya telefoni yanditswe' },
});


Object.assign(UI, {
  'Gifts & Flowers': { en: 'Gifts & Flowers', fr: 'Cadeaux et fleurs', rw: 'Impano n’indabyo' },
  'No gift shops available yet.': { en: 'No gift shops available yet.', fr: 'Aucune boutique de cadeaux disponible pour le moment.', rw: 'Nta maduka y’impano arahari ubu.' },
});


Object.assign(UI, {
  'This store isn\'t available right now.': { en: "This store isn't available right now.", fr: 'Cette boutique n’est pas disponible pour le moment.', rw: 'Iri duka ntiriboneka ubu.' },
  'Go back': { en: 'Go back', fr: 'Retour', rw: 'Subira inyuma' },
  'Delivery from': { en: 'Delivery from', fr: 'Livraison à partir de', rw: 'Kohereza kuva kuri' },
  'Search': { en: 'Search', fr: 'Rechercher', rw: 'Shakisha' },
  'No items match your search.': { en: 'No items match your search.', fr: 'Aucun article ne correspond à votre recherche.', rw: 'Nta bicuruzwa bihuye n’ishakisha ryawe.' },
  'Nothing listed here yet.': { en: 'Nothing listed here yet.', fr: 'Rien de répertorié ici pour le moment.', rw: 'Nta kintu cyashyizwe hano kugeza ubu.' },
  'Your basket': { en: 'Your basket', fr: 'Votre panier', rw: 'Igitebo cyawe' },
  'Cash not accepted. Payment is processed before delivery.': { en: 'Cash not accepted. Payment is processed before delivery.', fr: 'Espèces non acceptées. Le paiement est effectué avant la livraison.', rw: 'Amafaranga mu ntoki ntiyemewe. Ubwishyu bukorwa mbere yo kugeza.' },
  'All goods are inspected by the rider before pickup to meet Zana security compliance.': { en: 'All goods are inspected by the rider before pickup to meet Zana security compliance.', fr: 'Tous les articles sont inspectés par le motard avant la prise en charge pour respecter les règles de sécurité de Zana.', rw: 'Ibicuruzwa byose bigenzurwa n’umumotari mbere yo kubitwara kugira ngo byubahirize umutekano wa Zana.' },
  'We need your location to create a code. Please allow location access.': { en: 'We need your location to create a code. Please allow location access.', fr: 'Nous avons besoin de votre position pour créer un code. Autorisez l’accès à la localisation.', rw: 'Dukeneye aho uri kugira ngo dukore kode. Emera ko tubona aho uri.' },
  'Could not create a code right now.': { en: 'Could not create a code right now.', fr: 'Impossible de créer un code maintenant.', rw: 'Ntibyashobotse gukora kode ubu.' },
  'Could not copy. Select and copy the text manually.': { en: 'Could not copy. Select and copy the text manually.', fr: 'Impossible de copier. Sélectionnez et copiez le texte manuellement.', rw: 'Ntibyashobotse gukoporora. Hitamo wandike cyangwa ukoporore inyandiko ubwawe.' },
  'Could not copy the code. Select and copy it manually.': { en: 'Could not copy the code. Select and copy it manually.', fr: 'Impossible de copier le code. Sélectionnez-le et copiez-le manuellement.', rw: 'Ntibyashobotse gukoporora kode. Yihitemo uyikoporore ubwawe.' },
  'Generate a short code for this exact spot and send it to whoever is delivering to you. They enter it in Zana and your location appears on their map — no address needed.': { en: 'Generate a short code for this exact spot and send it to whoever is delivering to you. They enter it in Zana and your location appears on their map — no address needed.', fr: 'Générez un code court pour cet endroit précis et envoyez-le au livreur. Il le saisit dans Zana et votre position apparaît sur sa carte — aucune adresse nécessaire.', rw: 'Kora kode ngufi y’aha hantu nyir’izina uyohereze uyizana. Ayandike muri Zana maze aho uri hagaragarire ku ikarita ye — nta aderesi ikenewe.' },
  'Creating code…': { en: 'Creating code…', fr: 'Création du code…', rw: 'Turimo gukora kode…' },
  'Expires in': { en: 'Expires in', fr: 'Expire dans', rw: 'Irangira mu' },
  'Copied': { en: 'Copied', fr: 'Copié', rw: 'Byakoporowe' },
  'Copy code': { en: 'Copy code', fr: 'Copier le code', rw: 'Koporora kode' },
  'Share': { en: 'Share', fr: 'Partager', rw: 'Sangiza' },
  "The code works once and expires after 15 minutes, so your location isn't shared any longer than needed.": { en: "The code works once and expires after 15 minutes, so your location isn't shared any longer than needed.", fr: 'Le code fonctionne une fois et expire après 15 minutes, afin que votre position ne soit pas partagée plus longtemps que nécessaire.', rw: 'Kode ikoreshwa rimwe kandi ikarangira nyuma y’iminota 15, kugira ngo aho uri hatasangizwa igihe kirenze ibikenewe.' },
  'Generate a new code': { en: 'Generate a new code', fr: 'Générer un nouveau code', rw: 'Kora indi kode' },
  'Enter the code': { en: 'Enter the code', fr: 'Entrez le code', rw: 'Andika kode' },
  'Invalid code.': { en: 'Invalid code.', fr: 'Code invalide.', rw: 'Kode si yo.' },
  'Code sent to': { en: 'Code sent to', fr: 'Code envoyé à', rw: 'Kode yoherejwe kuri' },
  'your email': { en: 'your email', fr: 'votre e-mail', rw: 'imeyili yawe' },
  'Could not send a new code.': { en: 'Could not send a new code.', fr: 'Impossible d’envoyer un nouveau code.', rw: 'Ntibyashobotse kohereza indi kode.' },
  'Sent by email to': { en: 'Sent by email to', fr: 'Envoyé par e-mail à', rw: 'Yoherejwe kuri imeyili ya' },
  'Sent via SMS to': { en: 'Sent via SMS to', fr: 'Envoyé par SMS à', rw: 'Yoherejwe kuri SMS kuri' },
  'Verifying…': { en: 'Verifying…', fr: 'Vérification…', rw: 'Turagenzura…' },
  'Verify': { en: 'Verify', fr: 'Vérifier', rw: 'Genzura' },
  'Resend in': { en: 'Resend in', fr: 'Renvoyer dans', rw: 'Ongera wohereze mu' },
  'Resend code': { en: 'Resend code', fr: 'Renvoyer le code', rw: 'Ongera wohereze kode' },
  'Didn’t get it? Send to email instead': { en: 'Didn’t get it? Send to email instead', fr: 'Vous ne l’avez pas reçu ? Envoyer plutôt par e-mail', rw: 'Ntabwo wayibonye? Ohereza kuri imeyili aho' },
});


Object.assign(UI, {
  'Gym': { en: 'Gym', fr: 'Salle de sport', rw: 'Siporo' },
  'School': { en: 'School', fr: 'École', rw: 'Ishuri' },
});


Object.assign(UI, {
  'Order details': { en: 'Order details', fr: 'Détails de la commande', rw: 'Ibisobanuro by’itegeko' },
  'Note:': { en: 'Note:', fr: 'Note :', rw: 'Icyitonderwa:' },
  'Cancelling…': { en: 'Cancelling…', fr: 'Annulation…', rw: 'Turahagarika…' },
  'Cancel order': { en: 'Cancel order', fr: 'Annuler la commande', rw: 'Hagarika itegeko' },
});

// Inner-page localization sweep sync: verify customer sub-pages in production.


Object.assign(UI, {
  'Car Ride': { en: 'Car Ride', fr: 'Course en voiture', rw: 'Urugendo rw’imodoka' },
  'Car': { en: 'Car', fr: 'Voiture', rw: 'Imodoka' },
  'Comfortable': { en: 'Comfortable', fr: 'Confortable', rw: 'Yorohewe' },
  'Redeem': { en: 'Redeem', fr: 'Échanger', rw: 'Koresha amanota' },
  'Minimum 100 points': { en: 'Minimum 100 points', fr: 'Minimum 100 points', rw: 'Nibura amanota 100' },
  'points redeemed for': { en: 'points redeemed for', fr: 'points échangés contre', rw: 'amanota yakoreshejwe ku mafaranga' },
  'Could not redeem points': { en: 'Could not redeem points', fr: 'Impossible d’échanger les points', rw: 'Ntibyashobotse gukoresha amanota' },
  'value': { en: 'value', fr: 'valeur', rw: 'agaciro' },
  'earned total': { en: 'earned total', fr: 'total gagné', rw: 'yose wabonye' },
  'Per ride': { en: 'Per ride', fr: 'Par course', rw: 'Kuri buri rugendo' },
  '1 point per 100 RWF spent': { en: '1 point per 100 RWF spent', fr: '1 point pour 100 RWF dépensés', rw: 'Inota 1 kuri buri 100 RWF ukoresheje' },
  'Per delivery': { en: 'Per delivery', fr: 'Par livraison', rw: 'Kuri buri kwohereza' },
  '1 point per 200 RWF spent': { en: '1 point per 200 RWF spent', fr: '1 point pour 200 RWF dépensés', rw: 'Inota 1 kuri buri 200 RWF ukoresheje' },
  'Rate a driver': { en: 'Rate a driver', fr: 'Noter un chauffeur', rw: 'Tanga amanota ku mushoferi' },
  '+2 bonus points': { en: '+2 bonus points', fr: '+2 points bonus', rw: '+2 amanota y’inyongera' },
  'First ride ever': { en: 'First ride ever', fr: 'Première course', rw: 'Urugendo rwa mbere' },
  '+5 bonus points': { en: '+5 bonus points', fr: '+5 points bonus', rw: '+5 amanota y’inyongera' },
  '100 points = 500 RWF wallet credit (min 100 points)': { en: '100 points = 500 RWF wallet credit (min 100 points)', fr: '100 points = 500 RWF crédités au portefeuille (minimum 100 points)', rw: 'Amanota 100 = 500 RWF ashyirwa muri wallet (nibura amanota 100)' },
  'Points to redeem': { en: 'Points to redeem', fr: 'Points à échanger', rw: 'Amanota ushaka gukoresha' },
});
\nObject.assign(UI, {\n  'Calling': { en: 'Calling', fr: 'Appel en cours', rw: 'Turahamagara' },\n  'Connecting...': { en: 'Connecting...', fr: 'Connexion...', rw: 'Birimo guhuza...' },\n  'Reconnecting...': { en: 'Reconnecting...', fr: 'Reconnexion...', rw: 'Birimo kongera guhuza...' },\n  'Call ended': { en: 'Call ended', fr: 'Appel terminé', rw: 'Guhamagara byarangiye' },\n  'Unable to connect': { en: 'Unable to connect', fr: 'Impossible de se connecter', rw: 'Ntibyashobotse guhuza' },\n  'Zana Free Call · Connected': { en: 'Zana Free Call · Connected', fr: 'Zana · Appel gratuit · Connecté', rw: 'Zana · Guhamagara ku buntu · Byahujwe' },\n  'Unmute': { en: 'Unmute', fr: 'Activer le son', rw: 'Fungura mikoro' },\n  'Mute': { en: 'Mute', fr: 'Couper le son', rw: 'Zimya mikoro' },\n  'End call': { en: 'End call', fr: 'Terminer l’appel', rw: 'Soza guhamagara' },\n  'Speaker': { en: 'Speaker', fr: 'Haut-parleur', rw: 'Indangururamajwi' },\n  'WhatsApp Support': { en: 'WhatsApp Support', fr: 'Assistance WhatsApp', rw: 'Ubufasha kuri WhatsApp' },\n  'Call Emergency (112)': { en: 'Call Emergency (112)', fr: 'Appeler les urgences (112)', rw: 'Hamagara ubutabazi (112)' },\n  'Deliver to': { en: 'Deliver to', fr: 'Livrer à', rw: 'Bigezwe kuri' },\n  'Myself': { en: 'Myself', fr: 'Moi-même', rw: 'Jye ubwanjye' },\n  'Someone else': { en: 'Someone else', fr: 'Quelqu’un d’autre', rw: 'Undi muntu' },\n  'Recipient full name': { en: 'Recipient full name', fr: 'Nom complet du destinataire', rw: 'Amazina yose y’uwakira' },\n  'Recipient phone number': { en: 'Recipient phone number', fr: 'Numéro de téléphone du destinataire', rw: 'Numero ya telefoni y’uwakira' },\n  'Delivery address': { en: 'Delivery address', fr: 'Adresse de livraison', rw: 'Aderesi yo kugeza' },\n  "Drag the pin to the recipient's exact location. The order sends these coordinates with the address.": { en: "Drag the pin to the recipient's exact location. The order sends these coordinates with the address.", fr: "Faites glisser le repère jusqu’à l’emplacement exact du destinataire. La commande envoie ces coordonnées avec l’adresse.", rw: 'Kurura ikimenyetso ujye aho uwakira ari. Ibyo byerekezo byoherezwa hamwe na aderesi.' },\n  'Use current location': { en: 'Use current location', fr: 'Utiliser ma position actuelle', rw: 'Koresha aho ndi ubu' },\n  'Delivery note (optional)': { en: 'Delivery note (optional)', fr: 'Note de livraison (facultatif)', rw: 'Icyitonderwa cyo kugeza (si ngombwa)' },\n  'The account holder pays. The recipient only receives the order.': { en: 'The account holder pays. The recipient only receives the order.', fr: 'Le titulaire du compte paie. Le destinataire reçoit seulement la commande.', rw: 'Ufite konti ni we wishyura. Uwakira ni we gusa ubona ibyo yatumije.' },\n  'Your saved delivery location': { en: 'Your saved delivery location', fr: 'Votre lieu de livraison enregistré', rw: 'Aho wabikije ko ari ho bigezwa' },\n  'Chat with driver': { en: 'Chat with driver', fr: 'Discuter avec le chauffeur', rw: 'Ganira n’umushoferi' },\n  'Chat with courier': { en: 'Chat with courier', fr: 'Discuter avec le coursier', rw: 'Ganira n’utanga ibintu' },\n  'Thanks for rating': { en: 'Thanks for rating', fr: 'Merci pour votre évaluation', rw: 'Urakoze gutanga amanota' },\n  'Submitting…': { en: 'Submitting…', fr: 'Envoi…', rw: 'Birimo koherezwa…' },\n  'Submit Rating': { en: 'Submit Rating', fr: 'Envoyer la note', rw: 'Ohereza amanota' },\n  'Send report to Zana Safety': { en: 'Send report to Zana Safety', fr: 'Envoyer le signalement à la sécurité Zana', rw: 'Ohereza raporo kuri Zana Safety' },\n  'Saving…': { en: 'Saving…', fr: 'Enregistrement…', rw: 'Birimo kubikwa…' },\n  'Submit rating': { en: 'Submit rating', fr: 'Envoyer la note', rw: 'Ohereza amanota' },\n  'Poor': { en: 'Poor', fr: 'Mauvais', rw: 'Nabi' },\n  'Not great': { en: 'Not great', fr: 'Pas très bien', rw: 'Ntabwo ari byiza cyane' },\n  'Fine': { en: 'Fine', fr: 'Correct', rw: 'Ni byiza' },\n  'Good': { en: 'Good', fr: 'Bien', rw: 'Byiza' },\n  'Excellent': { en: 'Excellent', fr: 'Excellent', rw: 'Ni byiza cyane' },\n});\n\nObject.assign(UI, {\n  "Use this device's current location": { en: "Use this device's current location", fr: "Utiliser la position actuelle de cet appareil", rw: "Koresha aho iki gikoresho kiri ubu" },\n});\n