default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_KEY_PATH"],
      in_house: false
    )

    build_app(
      workspace: "App.xcworkspace",
      scheme: "App",
      export_method: "app-store",
      xcargs: "DEVELOPMENT_TEAM=TVNH48NRJX",
      export_options: {
        teamID: "TVNH48NRJX",
        provisioningProfiles: {
          ENV["BUNDLE_ID"] => ENV["PROFILE_NAME"]
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
