'use client';

import { useEffect, useState } from 'react';
import AdminShell from '../../../components/AdminShell';
import { api } from '../../../lib/api/client';
import { CheckCircle2, CreditCard, Eye, EyeOff, RefreshCw, Save, ShieldCheck, Wifi, Bike, CarFront, Store, Sparkles } from 'lucide-react';
import { getAiSettings, saveAiSettings, testAiConnection, type ZanaAiSettings, type ZanaAiProvider } from '../../../lib/api/admin';

type PaymentSettings = { enabled:boolean; environment:'sandbox'|'production'; baseUrl:string; rail:'mtn_momo'|'airtel_money'; minWithdrawal:number; configured:boolean; apiKeyHint?:string|null; webhookConfigured?:boolean };
type WooshPaySettings = { enabled:boolean; environment:'sandbox'|'production'; baseUrl:string; provider:'mtn_rw'|'airtel_rw'; minPayout:number; configured:boolean; apiKeyHint?:string|null; webhookConfigured?:boolean; capabilities?: { currency:string; collection:boolean; payout:boolean; mobileMoney:string[]; minimumPayout:number; maximumPayout:number } };
type Fare = { serviceType:'BIKE'|'ECONOMY'|'COMFORT'; base:number; perKm:number; bookingFee:number; minimum:number; commissionRate:number; freeWaitingMinutes:number; waitingPerMinute:number };
type MarketConfig = { id?:string; autoApprovePercent:number; hardRejectPercent:number; markupPercent:number; agentEarningRate:number; zanaMarkupShare:number; agentMarkupShare:number };
const fareLabels:any={BIKE:{name:'Moto / Bike',icon:Bike},ECONOMY:{name:'Economy Car',icon:CarFront},COMFORT:{name:'Premium Car',icon:CarFront}};
const fareFields:any=[['base','Base fare','RWF'],['perKm','Per kilometer','RWF / km'],['bookingFee','Booking fee','RWF'],['minimum','Minimum fare','RWF'],['commissionRate','ZANA commission','%'],['freeWaitingMinutes','Free waiting','minutes'],['waitingPerMinute','Waiting charge','RWF / min']];
const defaultMarket:MarketConfig={autoApprovePercent:15,hardRejectPercent:100,markupPercent:20,agentEarningRate:40,zanaMarkupShare:60,agentMarkupShare:40};

export default function SettingsPage(){
 const [payment,setPayment]=useState<PaymentSettings>({enabled:false,environment:'sandbox',baseUrl:'https://api.eversend.co/v1',rail:'mtn_momo',minWithdrawal:1000,configured:false});
 const [woosh,setWoosh]=useState<WooshPaySettings>({enabled:false,environment:'sandbox',baseUrl:'https://apitest.wooshpay.com/v1',provider:'mtn_rw',minPayout:980,configured:false});
 const [wooshKey,setWooshKey]=useState(''); const [wooshWebhook,setWooshWebhook]=useState(''); const [showWooshKey,setShowWooshKey]=useState(false); const [showWooshWebhook,setShowWooshWebhook]=useState(false); const [wooshTesting,setWooshTesting]=useState(false);
 const [fares,setFares]=useState<Fare[]>([]); const [fareEdits,setFareEdits]=useState<Record<string,Partial<Fare>>>({});
 const [market,setMarket]=useState<MarketConfig>(defaultMarket); const [apiKey,setApiKey]=useState(''); const [webhookSecret,setWebhookSecret]=useState('');
 const [showKey,setShowKey]=useState(false); const [showWebhook,setShowWebhook]=useState(false); const [saving,setSaving]=useState<string|null>(null);
 const [ai,setAi]=useState<ZanaAiSettings>({enabled:false,provider:'gemini',model:'gemini-3.8-flash',configured:false,apiKeyHint:null,features:{customerChat:true,rideBooking:true,foodOrdering:true,marketShopping:true,deliveryBooking:true,placeDiscovery:true},providers:{gemini:{enabled:false,model:'gemini-3.8-flash',configured:false,features:{customerChat:true,rideBooking:true,foodOrdering:true,marketShopping:true,deliveryBooking:true,placeDiscovery:true}},groq:{enabled:false,model:'openai/gpt-oss-120b',configured:false,features:{customerChat:true,rideBooking:true,foodOrdering:true,marketShopping:true,deliveryBooking:true,placeDiscovery:true}},openrouter:{enabled:false,model:'openrouter/free',configured:false,features:{customerChat:true,rideBooking:true,foodOrdering:true,marketShopping:true,deliveryBooking:true,placeDiscovery:true}}}}); const [aiKey,setAiKey]=useState(''); const [showAiKey,setShowAiKey]=useState(false); const [aiTesting,setAiTesting]=useState(false); const [testing,setTesting]=useState(false); const [message,setMessage]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
 const load=async()=>{try{const [p,w,f,m,a]=await Promise.all([api.get<PaymentSettings>('/admin/settings/payments/eversend'),api.get<WooshPaySettings>('/admin/settings/payments/wooshpay'),api.get<Fare[]>('/admin/fares'),api.get<MarketConfig>('/admin/settings/marketplace'),getAiSettings()]);setPayment(p);setWoosh(w);setFares(f);setMarket({...defaultMarket,...m});setAi({...a, providers: a.providers ?? {gemini:{...a,model:a.model||'gemini-3.8-flash'},groq:{...a,model:'openai/gpt-oss-120b'},openrouter:{...a,model:'openrouter/free'}}});}catch(e:any){setError(e?.message??'Could not load settings.');}};
 useEffect(()=>{load();},[]);
 const savePayment=async()=>{setSaving('payment');setMessage(null);setError(null);try{const n=await api.patch<any>('/admin/settings/payments/eversend',{enabled:payment.enabled,environment:payment.environment,apiKey:apiKey.trim()||undefined,webhookSecret:webhookSecret.trim()||undefined,baseUrl:payment.baseUrl,rail:payment.rail,minWithdrawal:payment.minWithdrawal});setPayment(n);setApiKey('');setWebhookSecret('');setMessage('Eversend settings saved securely.');}catch(e:any){setError(e?.message??'Could not save payment settings.');}finally{setSaving(null);}};
 const saveWoosh=async()=>{setSaving('woosh');setMessage(null);setError(null);try{const n=await api.patch<WooshPaySettings>('/admin/settings/payments/wooshpay',{enabled:woosh.enabled,environment:woosh.environment,apiKey:wooshKey.trim()||undefined,webhookSecret:wooshWebhook.trim()||undefined,baseUrl:woosh.baseUrl,provider:woosh.provider,minPayout:woosh.minPayout});setWoosh(n);setWooshKey('');setWooshWebhook('');setMessage('WooshPay settings saved securely.');}catch(e:any){setError(e?.message??'Could not save WooshPay settings.');}finally{setSaving(null);}};
 const testWoosh=async()=>{setWooshTesting(true);setMessage(null);setError(null);try{const n=await api.post<any>('/admin/settings/payments/wooshpay/test');setMessage(`WooshPay connection succeeded (${n.environment}).`);}catch(e:any){setError(e?.message??'WooshPay connection test failed.');}finally{setWooshTesting(false);}};
 const testPayment=async()=>{setTesting(true);setMessage(null);setError(null);try{await api.post('/admin/settings/payments/eversend/test');setMessage('Eversend connection test succeeded.');}catch(e:any){setError(e?.message??'Eversend connection test failed.');}finally{setTesting(false);}};
 const saveFare=async(f:Fare)=>{const edits=fareEdits[f.serviceType];if(!edits||!Object.keys(edits).length)return;setSaving('fare:'+f.serviceType);setMessage(null);setError(null);try{await api.patch('/admin/fares/'+f.serviceType,edits);setFareEdits(v=>({...v,[f.serviceType]:{}}));setFares(await api.get<Fare[]>('/admin/fares'));setMessage(fareLabels[f.serviceType].name+' pricing policy is now live.');}catch(e:any){setError(e?.message??'Could not save fare policy.');}finally{setSaving(null);}};
 const saveMarket=async()=>{if(Math.abs(Number(market.agentMarkupShare)+Number(market.zanaMarkupShare)-100)>0.001){setError('Agent markup share and Zana markup share must equal 100%.');return;}setSaving('market');setMessage(null);setError(null);try{const n=await api.patch<MarketConfig>('/admin/settings/marketplace',market);setMarket({...defaultMarket,...n});setMessage('Marketplace pricing policy is now live.');}catch(e:any){setError(e?.message??'Could not save marketplace settings.');}finally{setSaving(null);}};
 const setFare=(serviceType:string,key:string,raw:string)=>{const n=Number(raw);setFareEdits(v=>({...v,[serviceType]:{...(v[serviceType]??{}),[key]:Number.isFinite(n)?n:0}}));};
 const toggleAiFeature=(key:keyof ZanaAiSettings['features'])=>setAi(s=>({...s,features:{...s.features,[key]:!s.features[key]}}));
 const selectAiProvider=(provider:ZanaAiProvider)=>{const p=ai.providers?.[provider] ?? {enabled:false,model:provider==='gemini'?'gemini-3.8-flash':provider==='groq'?'openai/gpt-oss-120b':'openrouter/free',configured:false,apiKeyHint:null,features:ai.features};setAi(s=>({...s,provider,enabled:p.enabled,model:p.model,configured:p.configured,apiKeyHint:p.apiKeyHint,features:p.features}));setAiKey('');};
 const saveAi=async()=>{setSaving('ai');setMessage(null);setError(null);try{const n=await saveAiSettings({provider:ai.provider,enabled:ai.enabled,model:ai.model.trim(),apiKey:aiKey.trim()||undefined,features:ai.features});setAi(n);setAiKey('');setMessage(`${ai.provider} AI settings saved securely.`);}catch(e:any){setError(e?.message??'Could not save AI settings.');}finally{setSaving(null);}};
 const testAi=async()=>{setAiTesting(true);setMessage(null);setError(null);try{const n=await testAiConnection();setMessage(n.response?`${n.provider||ai.provider} connection succeeded: ${n.response}`:`${n.provider||ai.provider} connection succeeded.`);}catch(e:any){setError(e?.message??'Gemini connection test failed.');}finally{setAiTesting(false);}};
 const removeAiKey=async()=>{setSaving('ai');setMessage(null);setError(null);try{const n=await saveAiSettings({provider:ai.provider,enabled:ai.enabled,model:ai.model,clearApiKey:true,features:ai.features});setAi(n);setAiKey('');setMessage(`${ai.provider} API key removed.`);}catch(e:any){setError(e?.message??'Could not remove Gemini API key.');}finally{setSaving(null);}};
 return <AdminShell><div className="space-y-6 max-w-6xl">
  <div><h1 className="text-2xl font-bold text-gray-900">Settings</h1><p className="text-sm text-gray-500 mt-1">All Zana policies and external payment configuration are controlled here. Operational records stay in their respective sections.</p></div>
  {(message||error)&&<div className={`rounded-xl border p-3 text-sm ${error?'bg-red-50 border-red-100 text-red-700':'bg-green-50 border-green-100 text-green-700'}`}>{error||message}</div>}
  <section className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="p-5 border-b border-gray-100"><div className="flex items-center gap-3"><Store size={20} className="text-zana-primary"/><div><h2 className="font-bold text-gray-900">Marketplace pricing</h2><p className="text-xs text-gray-500">Customer markup and the split between market agents and Zana.</p></div></div></div><div className="p-5"><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{[['markupPercent','Customer markup'],['autoApprovePercent','Auto-approve price change'],['hardRejectPercent','Hard-reject price change'],['agentMarkupShare','Agent markup share'],['zanaMarkupShare','Zana markup share'],['agentEarningRate','Agent earning rate']].map(([k,l])=><label key={k} className="block"><span className="text-xs font-semibold text-gray-600">{l} (%)</span><input type="number" min="0" max="100" step="0.1" value={(market as any)[k]??0} onChange={e=>setMarket(v=>({...v,[k]:Number(e.target.value)||0}))} className="mt-1.5 w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm font-semibold"/></label>)}</div><p className="text-xs text-gray-500 mt-3">Existing paid orders keep their locked pricing. These values apply to future marketplace activity.</p><button onClick={saveMarket} disabled={saving==='market'} className="mt-4 inline-flex items-center gap-2 bg-zana-primary text-white font-semibold px-4 py-2.5 rounded-lg text-sm disabled:opacity-50"><Save size={15}/>{saving==='market'?'Saving…':'Save marketplace settings'}</button></div></section>
  <section className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="p-5 border-b border-gray-100"><div className="flex items-center gap-3"><ShieldCheck size={20} className="text-zana-primary"/><div><h2 className="font-bold text-gray-900">Ride pricing & commission</h2><p className="text-xs text-gray-500">Live fare cards for every ride class.</p></div></div></div><div className="p-5 grid xl:grid-cols-3 gap-4">{fares.map(f=>{const meta=fareLabels[f.serviceType]||{name:f.serviceType,icon:CarFront};const Icon=meta.icon;const edits=fareEdits[f.serviceType]||{};const dirty=Object.keys(edits).length>0;return <div key={f.serviceType} className="border border-gray-200 rounded-xl overflow-hidden"><div className="p-4 border-b border-gray-100 flex items-center gap-3"><Icon size={18} className="text-zana-primary"/><h3 className="font-bold text-gray-900">{meta.name}</h3></div><div className="p-4 space-y-3">{fareFields.map(([k,l,u]:any)=><label key={k} className="block"><div className="flex justify-between"><span className="text-xs font-semibold text-gray-600">{l}</span><span className="text-[10px] text-gray-400">{u}</span></div><input type="number" min="0" step={k==='commissionRate'?'0.1':'1'} value={(edits as any)[k]??(f as any)[k]} onChange={e=>setFare(f.serviceType,k,e.target.value)} className="mt-1 w-full border border-gray-200 rounded-lg px-3 py-2 text-sm"/></label>)}<button onClick={()=>saveFare(f)} disabled={!dirty||saving==='fare:'+f.serviceType} className="w-full inline-flex justify-center items-center gap-2 bg-zana-primary text-white font-bold py-2.5 rounded-lg text-sm disabled:opacity-40"><Save size={14}/>{saving==='fare:'+f.serviceType?'Saving…':dirty?'Apply live fare policy':'No pending changes'}</button></div></div>})}</div></section>
  <section className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="p-5 border-b border-gray-100"><div className="flex items-center gap-3"><Sparkles size={20} className="text-zana-primary"/><div><h2 className="font-bold text-gray-900">Zana AI</h2><p className="text-xs text-gray-500">Configure Gemini, Groq and OpenRouter. Zana automatically falls back to another configured provider when one is unavailable.</p></div></div></div><div className="p-5 space-y-5">
   <label className="flex items-center justify-between gap-4 p-3 rounded-xl bg-gray-50"><div><div className="text-sm font-semibold text-gray-900">Enable Zana AI</div><div className="text-xs text-gray-500">Turn the AI service on for supported customer experiences.</div></div><button onClick={()=>setAi(s=>({...s,enabled:!s.enabled}))} className={`relative w-11 h-6 rounded-full ${ai.enabled?'bg-zana-primary':'bg-gray-300'}`}><span className={`absolute top-1 w-4 h-4 bg-white rounded-full ${ai.enabled?'left-6':'left-1'}`}/></button></label>
   <div className="grid md:grid-cols-3 gap-2">{(['gemini','groq','openrouter'] as ZanaAiProvider[]).map(provider=><button key={provider} type="button" onClick={()=>selectAiProvider(provider)} className={`rounded-lg border px-3 py-3 text-left ${ai.provider===provider?'border-zana-primary bg-green-50':'border-gray-200 bg-white'}`}><div className="font-bold text-sm capitalize">{provider}</div><div className="text-[11px] text-gray-500 mt-1">{ai.providers[provider]?.configured?'API key configured':'API key not configured'}</div></button>)}</div>
   <div className="grid md:grid-cols-2 gap-4"><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">{ai.provider} model</span><input value={ai.model} onChange={e=>setAi(s=>({...s,model:e.target.value}))} placeholder="Model ID" className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm font-mono"/></label><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">{ai.provider} API key</span><div className="relative"><input value={aiKey} onChange={e=>setAiKey(e.target.value)} type={showAiKey?'text':'password'} placeholder={ai.apiKeyHint?`Saved: ${ai.apiKeyHint} — leave blank to keep it`:`Paste ${ai.provider} API key`} autoComplete="new-password" className="w-full border border-gray-200 rounded-lg px-3 py-2.5 pr-10 text-sm font-mono"/><button type="button" onClick={()=>setShowAiKey(v=>!v)} className="absolute right-3 top-2.5 text-gray-400">{showAiKey?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label></div>
   <div><div className="text-xs font-semibold text-gray-600 mb-2">Zana AI capabilities</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2">{([['customerChat','Customer Chat'],['rideBooking','Ride Booking'],['foodOrdering','Food Ordering'],['marketShopping','Market Shopping'],['deliveryBooking','Delivery Booking'],['placeDiscovery','Place Discovery']] as const).map(([key,label])=><button key={key} type="button" onClick={()=>toggleAiFeature(key)} className={`flex items-center justify-between rounded-lg border px-3 py-2.5 text-sm font-semibold text-left ${ai.features[key]?'border-green-200 bg-green-50 text-green-800':'border-gray-200 bg-white text-gray-500'}`}><span>{label}</span><span className={`w-2.5 h-2.5 rounded-full ${ai.features[key]?'bg-zana-primary':'bg-gray-300'}`}/></button>)}</div></div>
   <div className="flex flex-wrap gap-2"><button onClick={saveAi} disabled={saving==='ai'} className="flex items-center gap-2 bg-zana-primary text-white font-semibold px-4 py-2.5 rounded-lg disabled:opacity-50"><Save size={16}/>{saving==='ai'?'Saving…':`Save ${ai.provider} settings`}</button><button onClick={testAi} disabled={aiTesting||!ai.configured} className="flex items-center gap-2 border border-gray-200 text-gray-700 font-semibold px-4 py-2.5 rounded-lg disabled:opacity-40">{aiTesting?<RefreshCw size={16} className="animate-spin"/>:<Wifi size={16}/>} {aiTesting?'Testing…':`Test ${ai.provider} connection`}</button>{ai.configured&&<button onClick={removeAiKey} disabled={saving==='ai'} className="flex items-center gap-2 border border-red-200 text-red-700 font-semibold px-4 py-2.5 rounded-lg disabled:opacity-40">Remove API key</button>}</div>
   <div className="pt-3 border-t border-gray-100 grid md:grid-cols-3 gap-3 text-xs text-gray-500"><div className="flex gap-2"><ShieldCheck size={15} className="text-zana-primary shrink-0"/>Key encrypted at rest on the backend.</div><div className="flex gap-2"><EyeOff size={15} className="text-zana-primary shrink-0"/>The full key is never returned to the admin web.</div><div className="flex gap-2"><CheckCircle2 size={15} className="text-zana-primary shrink-0"/>Gemini is called server-side only.</div></div>
  </div></section>
  <section className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="p-5 border-b border-gray-100 flex items-center justify-between"><div className="flex items-center gap-3"><CreditCard size={20} className="text-zana-primary"/><div><h2 className="font-bold text-gray-900">WooshPay payments</h2><p className="text-xs text-gray-500">Rwanda Mobile Money collections and payouts.</p></div></div><span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${woosh.configured?'bg-green-50 text-green-700':'bg-gray-100 text-gray-500'}`}>{woosh.configured?'Configured':'Not configured'}</span></div><div className="p-5 space-y-5">
   <label className="flex items-center justify-between gap-4 p-3 rounded-xl bg-gray-50"><div><div className="text-sm font-semibold text-gray-900">Enable WooshPay</div><div className="text-xs text-gray-500">Use WooshPay for supported collections and payouts.</div></div><button onClick={()=>setWoosh(s=>({...s,enabled:!s.enabled}))} className={`relative w-11 h-6 rounded-full ${woosh.enabled?'bg-zana-primary':'bg-gray-300'}`}><span className={`absolute top-1 w-4 h-4 bg-white rounded-full ${woosh.enabled?'left-6':'left-1'}`}/></button></label>
   <div className="grid md:grid-cols-2 gap-4"><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">Environment</span><select value={woosh.environment} onChange={e=>setWoosh(s=>({...s,environment:e.target.value as any,baseUrl:e.target.value==='production'?'https://api.wooshpay.com/v1':'https://apitest.wooshpay.com/v1'}))} className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm bg-white"><option value="sandbox">Sandbox</option><option value="production">Production</option></select></label><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">Rwanda Mobile Money provider</span><select value={woosh.provider} onChange={e=>setWoosh(s=>({...s,provider:e.target.value as any}))} className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm bg-white"><option value="mtn_rw">MTN Rwanda</option><option value="airtel_rw">Airtel Rwanda</option></select></label></div>
   <label className="block"><span className="text-xs font-semibold text-gray-600 block mb-1.5">WooshPay API key</span><div className="relative"><input value={wooshKey} onChange={e=>setWooshKey(e.target.value)} type={showWooshKey?'text':'password'} placeholder={woosh.apiKeyHint?`Saved: ${woosh.apiKeyHint} — leave blank to keep it`:'Paste WooshPay API key'} autoComplete="new-password" className="w-full border border-gray-200 rounded-lg px-3 py-2.5 pr-10 text-sm font-mono"/><button type="button" onClick={()=>setShowWooshKey(v=>!v)} className="absolute right-3 top-2.5 text-gray-400">{showWooshKey?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>
   <label className="block"><span className="text-xs font-semibold text-gray-600 block mb-1.5">Webhook secret <span className="font-normal text-gray-400">(recommended)</span></span><div className="relative"><input value={wooshWebhook} onChange={e=>setWooshWebhook(e.target.value)} type={showWooshWebhook?'text':'password'} placeholder={woosh.webhookConfigured?'Saved — leave blank to keep it':'whsec_…'} autoComplete="new-password" className="w-full border border-gray-200 rounded-lg px-3 py-2.5 pr-10 text-sm font-mono"/><button type="button" onClick={()=>setShowWooshWebhook(v=>!v)} className="absolute right-3 top-2.5 text-gray-400">{showWooshWebhook?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>
   <div className="grid md:grid-cols-2 gap-4"><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">API base URL</span><input value={woosh.baseUrl} onChange={e=>setWoosh(s=>({...s,baseUrl:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm font-mono"/></label><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">Minimum payout (RWF)</span><input type="number" min={980} step={100} value={woosh.minPayout} onChange={e=>setWoosh(s=>({...s,minPayout:Math.max(980,Number(e.target.value)||980)}))} className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm"/></label></div>
   <div className="flex flex-wrap gap-2"><button onClick={saveWoosh} disabled={saving==='woosh'} className="flex items-center gap-2 bg-zana-primary text-white font-semibold px-4 py-2.5 rounded-lg disabled:opacity-50"><Save size={16}/>{saving==='woosh'?'Saving…':'Save WooshPay settings'}</button><button onClick={testWoosh} disabled={wooshTesting||!woosh.configured} className="flex items-center gap-2 border border-gray-200 text-gray-700 font-semibold px-4 py-2.5 rounded-lg disabled:opacity-40">{wooshTesting?<RefreshCw size={16} className="animate-spin"/>:<Wifi size={16}/>} {wooshTesting?'Testing…':'Test connection'}</button></div>
   <div className="pt-3 border-t border-gray-100 grid md:grid-cols-3 gap-3 text-xs text-gray-500"><div className="flex gap-2"><ShieldCheck size={15} className="text-zana-primary shrink-0"/>Credentials are encrypted at rest.</div><div className="flex gap-2"><EyeOff size={15} className="text-zana-primary shrink-0"/>Full secrets are never returned to the browser.</div><div className="flex gap-2"><CheckCircle2 size={15} className="text-zana-primary shrink-0"/>Sandbox should be tested before production.</div></div>
  </div></section>
  <section className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="p-5 border-b border-gray-100 flex items-center justify-between"><div className="flex items-center gap-3"><CreditCard size={20} className="text-zana-primary"/><div><h2 className="font-bold text-gray-900">Eversend payments</h2><p className="text-xs text-gray-500">Collections, payouts, refunds and withdrawals.</p></div></div><span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${payment.configured?'bg-green-50 text-green-700':'bg-gray-100 text-gray-500'}`}>{payment.configured?'Configured':'Not configured'}</span></div><div className="p-5 space-y-5">
   <label className="flex items-center justify-between gap-4 p-3 rounded-xl bg-gray-50"><div><div className="text-sm font-semibold text-gray-900">Enable Eversend</div><div className="text-xs text-gray-500">Use Eversend for digital collections and payouts.</div></div><button onClick={()=>setPayment(s=>({...s,enabled:!s.enabled}))} className={`relative w-11 h-6 rounded-full ${payment.enabled?'bg-zana-primary':'bg-gray-300'}`}><span className={`absolute top-1 w-4 h-4 bg-white rounded-full ${payment.enabled?'left-6':'left-1'}`}/></button></label>
   <div className="grid md:grid-cols-2 gap-4"><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">Environment</span><select value={payment.environment} onChange={e=>setPayment(s=>({...s,environment:e.target.value as any}))} className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm bg-white"><option value="sandbox">Sandbox</option><option value="production">Production</option></select></label><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">Rwanda payout rail</span><select value={payment.rail} onChange={e=>setPayment(s=>({...s,rail:e.target.value as any}))} className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm bg-white"><option value="mtn_momo">MTN MoMo</option><option value="airtel_money">Airtel Money</option></select></label></div>
   <label className="block"><span className="text-xs font-semibold text-gray-600 block mb-1.5">Eversend API key</span><div className="relative"><input value={apiKey} onChange={e=>setApiKey(e.target.value)} type={showKey?'text':'password'} placeholder={payment.apiKeyHint?`Saved: ${payment.apiKeyHint} — leave blank to keep it`:'sk_test_… or sk_live_…'} autoComplete="new-password" className="w-full border border-gray-200 rounded-lg px-3 py-2.5 pr-10 text-sm font-mono"/><button type="button" onClick={()=>setShowKey(v=>!v)} className="absolute right-3 top-2.5 text-gray-400">{showKey?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>
   <label className="block"><span className="text-xs font-semibold text-gray-600 block mb-1.5">Webhook secret <span className="font-normal text-gray-400">(optional for now)</span></span><div className="relative"><input value={webhookSecret} onChange={e=>setWebhookSecret(e.target.value)} type={showWebhook?'text':'password'} placeholder={payment.webhookConfigured?'Saved — leave blank to keep it':'Webhook signing secret'} autoComplete="new-password" className="w-full border border-gray-200 rounded-lg px-3 py-2.5 pr-10 text-sm font-mono"/><button type="button" onClick={()=>setShowWebhook(v=>!v)} className="absolute right-3 top-2.5 text-gray-400">{showWebhook?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>
   <div className="grid md:grid-cols-2 gap-4"><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">API base URL</span><input value={payment.baseUrl} onChange={e=>setPayment(s=>({...s,baseUrl:e.target.value}))} className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm font-mono"/></label><label><span className="text-xs font-semibold text-gray-600 block mb-1.5">Minimum withdrawal (RWF)</span><input type="number" min={1000} step={100} value={payment.minWithdrawal} onChange={e=>setPayment(s=>({...s,minWithdrawal:Math.max(1000,Number(e.target.value)||1000)}))} className="w-full border border-gray-200 rounded-lg px-3 py-2.5 text-sm"/></label></div>
   <div className="flex flex-wrap gap-2"><button onClick={savePayment} disabled={saving==='payment'} className="flex items-center gap-2 bg-zana-primary text-white font-semibold px-4 py-2.5 rounded-lg disabled:opacity-50"><Save size={16}/>{saving==='payment'?'Saving…':'Save payment settings'}</button><button onClick={testPayment} disabled={testing||!payment.configured} className="flex items-center gap-2 border border-gray-200 text-gray-700 font-semibold px-4 py-2.5 rounded-lg disabled:opacity-40">{testing?<RefreshCw size={16} className="animate-spin"/>:<Wifi size={16}/>} {testing?'Testing…':'Test connection'}</button></div>
   <div className="pt-3 border-t border-gray-100 grid md:grid-cols-3 gap-3 text-xs text-gray-500"><div className="flex gap-2"><ShieldCheck size={15} className="text-zana-primary shrink-0"/>Credentials are encrypted at rest.</div><div className="flex gap-2"><EyeOff size={15} className="text-zana-primary shrink-0"/>Full secrets are never returned to the browser.</div><div className="flex gap-2"><CheckCircle2 size={15} className="text-zana-primary shrink-0"/>Sandbox first, then production.</div></div>
  </div></section>
 </div></AdminShell>;
}
