'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ShoppingBasket } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { fetchAgentEarnings, AgentEarnings } from '../../../lib/api/merchant';
const money=(n:number)=>n.toLocaleString()+' RWF';
export default function AgentEarningsPage(){
 const router=useRouter(); const [data,setData]=useState<AgentEarnings|null>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{fetchAgentEarnings().then(setData).finally(()=>setLoading(false));},[]);
 return <div className="p-4 pb-24 max-w-2xl mx-auto"><div className="flex items-center gap-3 mb-5"><button onClick={()=>router.back()} className="w-9 h-9 rounded-full bg-gray-100 flex items-center justify-center"><ArrowLeft size={18}/></button><div><h1 className="text-xl font-black">Agent earnings</h1><p className="text-xs text-gray-500">Your market markup share</p></div></div>
 {loading?<p className="text-center py-10 text-sm text-gray-500">Loading…</p>:!data?<p className="text-center py-10 text-sm text-red-600">Could not load earnings.</p>:<><div className="bg-zana-primary rounded-2xl p-5 text-white mb-4"><p className="text-xs text-white/70">Your settled earnings</p><p className="text-3xl font-black mt-1">{money(data.totalEarning)}</p><div className="grid grid-cols-2 gap-3 mt-4"><div><p className="text-[11px] text-white/60">Markup generated</p><p className="font-bold">{money(data.totalMarkup)}</p></div><div><p className="text-[11px] text-white/60">Your share</p><p className="font-bold">40%</p></div></div></div>
 <div className="bg-white rounded-2xl p-4 shadow-sm mb-4"><div className="flex items-center gap-2 mb-2"><ShoppingBasket size={16} className="text-zana-primary"/><p className="font-bold">Settlement</p></div><p className="text-xs text-gray-600 leading-5">Zana adds 20% to the underlying market price. That markup is split 60% to Zana and 40% to you. The underlying market price is not the earning pool.</p></div>
 <div className="space-y-2">{data.settlements.map(s=><div key={s.id} className="bg-white rounded-2xl p-4 shadow-sm"><div className="flex justify-between"><div><p className="font-mono text-[11px] font-bold text-zana-primary">{s.orderId.slice(0,8)}</p><p className="text-[11px] text-gray-400">{new Date(s.settledAt).toLocaleString()}</p></div><span className="font-black text-zana-primary">{money(s.agentEarning)}</span></div><div className="grid grid-cols-3 gap-2 mt-3 text-[11px]"><div><p className="text-gray-400">Market</p><p className="font-bold">{money(s.underlyingAmount??0)}</p></div><div><p className="text-gray-400">Customer</p><p className="font-bold">{money(s.customerAmount??0)}</p></div><div><p className="text-gray-400">Markup</p><p className="font-bold">{money(s.markupAmount??0)}</p></div></div><div className="flex justify-between mt-3 pt-3 border-t border-gray-100 text-xs"><span className="text-gray-500">Zana {s.zanaRate??60}%</span><span className="font-bold">You {s.agentRate??40}%</span></div></div>)}{!data.settlements.length&&<p className="text-center py-10 text-sm text-gray-500">No settled market orders yet.</p>}</div></>}
 </div>;
}