'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ReceiptText } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { fetchMerchantEarnings, MerchantEarnings, fetchWallet } from '../../lib/api/merchant';
const money = (n: number) => n.toLocaleString() + ' RWF';
export default function MerchantEarningsPage() {
  const router = useRouter(); const [data,setData]=useState<MerchantEarnings|null>(null); const [wallet,setWallet]=useState<number|null>(null); const [loading,setLoading]=useState(true);
  useEffect(()=>{ Promise.all([fetchMerchantEarnings(),fetchWallet()]).then(([e,w])=>{setData(e);setWallet(w.balance);}).finally(()=>setLoading(false)); },[]);
  return <div className="p-4 pb-24 max-w-2xl mx-auto">
    <div className="flex items-center gap-3 mb-5"><button onClick={()=>router.back()} className="w-9 h-9 rounded-full bg-gray-100 flex items-center justify-center"><ArrowLeft size={18}/></button><div><h1 className="text-xl font-black">Earnings</h1><p className="text-xs text-gray-500">Your merchant settlement ledger</p></div></div>
    {loading ? <p className="text-center py-10 text-sm text-gray-500">Loading…</p> : !data ? <p className="text-center py-10 text-sm text-red-600">Could not load earnings.</p> : <><div className="bg-zana-primary rounded-2xl p-5 text-white mb-4"><p className="text-xs text-white/70">Withdrawable wallet balance</p><p className="text-3xl font-black mt-1">{money(wallet ?? 0)}</p><div className="grid grid-cols-2 gap-3 mt-4"><div><p className="text-[11px] text-white/60">Settled merchant earnings</p><p className="font-bold">{money(data.totalNet)}</p></div><div><p className="text-[11px] text-white/60">Zana commission</p><p className="font-bold">{money(data.totalCommission)}</p></div></div></div>
    <div className="bg-white rounded-2xl p-4 shadow-sm mb-4"><div className="flex items-center gap-2 mb-2"><ReceiptText size={16} className="text-zana-primary"/><p className="font-bold">Settlement</p></div><p className="text-xs text-gray-600 leading-5">Zana keeps 15% of each completed merchandise sale. You receive 85%. Customer delivery fees are separate.</p></div>
    <div className="space-y-2">{data.settlements.map(s=><div key={s.id} className="bg-white rounded-2xl p-4 shadow-sm"><div className="flex justify-between"><div><p className="font-mono text-[11px] font-bold text-zana-primary">{s.orderId.slice(0,8)}</p><p className="text-[11px] text-gray-400">{new Date(s.settledAt).toLocaleString()}</p></div><span className="font-black">{money(s.merchantNet)}</span></div><div className="grid grid-cols-3 gap-2 mt-3 text-[11px]"><div><p className="text-gray-400">Sale</p><p className="font-bold">{money(s.grossAmount)}</p></div><div><p className="text-gray-400">15% Zana</p><p className="font-bold">{money(s.commissionAmount)}</p></div><div><p className="text-gray-400">You receive</p><p className="font-bold text-zana-primary">{money(s.merchantNet)}</p></div></div></div>)}{!data.settlements.length&&<p className="text-center py-10 text-sm text-gray-500">No settled sales yet.</p>}</div></>}
  </div>;
}