'use client';

export type Lang = 'en' | 'fr' | 'rw';

const STORAGE_KEY = 'zana_lang';

export const LANG_LABELS: Record<Lang, string> = {
  en: 'English',
  fr: 'Français',
  rw: 'Ikinyarwanda',
};

export function getStoredLang(): Lang {
  if (typeof window === 'undefined') return 'en';
  return (localStorage.getItem(STORAGE_KEY) as Lang) ?? 'en';
}

export function setStoredLang(lang: Lang) {
  if (typeof window === 'undefined') return;
  localStorage.setItem(STORAGE_KEY, lang);
}

// UI strings for the merchant app in all three languages.
export const UI: Record<string, Record<Lang, string>> = {
  'What do you need today?': { en: 'What do you need today?', fr: 'Que voulez-vous aujourd\'hui?', rw: 'Ukeneye iki uyu munsi?' },
  'Wallet Balance': { en: 'Wallet Balance', fr: 'Solde du portefeuille', rw: 'Amafaranga afite' },
  'Top Up': { en: 'Top Up', fr: 'Recharger', rw: 'Shyiramo amafaranga' },
  'Send My Location': { en: 'Send My Location', fr: 'Envoyer ma localisation', rw: 'Ohereza aho ndi' },
  'Share a code instead of explaining your address': { en: 'Share a code instead of explaining your address', fr: 'Partagez un code au lieu d\'expliquer votre adresse', rw: 'Ohereza kode aho gusobanura aho uri' },
  'Orders': { en: 'Orders', fr: 'Commandes', rw: 'Ibyagurijwe' },
  'Wallet': { en: 'Wallet', fr: 'Portefeuille', rw: 'Amafaranga' },
  'Profile': { en: 'Profile', fr: 'Profil', rw: 'Umwirondoro' },
  'Home': { en: 'Home', fr: 'Accueil', rw: 'Ahabanza' },
  'Chat': { en: 'Chat', fr: 'Discussion', rw: 'Ganira' },
  'Send': { en: 'Send', fr: 'Envoyer', rw: 'Ohereza' },
  'Type a message…': { en: 'Type a message…', fr: 'Écrivez un message…', rw: 'Andika ubutumwa…' },
  'Language': { en: 'Language', fr: 'Langue', rw: 'Ururimi' },
  "Confirm order": { en: "Confirm order", fr: "Confirmer la commande", rw: "Emeza itegeko" },
  "Start preparing": { en: "Start preparing", fr: "Commencer la préparation", rw: "Tangira gutegura" },
  "Ready for pickup": { en: "Ready for pickup", fr: "Prêt pour le retrait", rw: "Biteguye gufatwa" },
  "New order": { en: "New order", fr: "Nouvelle commande", rw: "Itegeko rishya" },
  "Confirmed": { en: "Confirmed", fr: "Confirmée", rw: "Byemejwe" },
  "Preparing": { en: "Preparing", fr: "En préparation", rw: "Birategurwa" },
  "Ready — driver en route": { en: "Ready — driver en route", fr: "Prêt — chauffeur en route", rw: "Biteguye — umushoferi ari mu nzira" },
  "Driver delivering": { en: "Driver delivering", fr: "Chauffeur en livraison", rw: "Umushoferi arageza" },
  "Delivered": { en: "Delivered", fr: "Livrée", rw: "Byagejejwe" },
  "Cancelled": { en: "Cancelled", fr: "Annulée", rw: "Byahagaritswe" },
  "Active": { en: "Active", fr: "Actives", rw: "Ibikora" },
  "Done": { en: "Done", fr: "Terminées", rw: "Byarangiye" },
  "All": { en: "All", fr: "Toutes", rw: "Byose" },
  "No orders here": { en: "No orders here", fr: "Aucune commande ici", rw: "Nta mategeko ari hano" },
  "Total": { en: "Total", fr: "Total", rw: "Byose hamwe" },
  "A Zana driver has been dispatched to collect this order.": { en: "A Zana driver has been dispatched to collect this order.", fr: "Un chauffeur Zana a été envoyé pour récupérer cette commande.", rw: "Umushoferi wa Zana yoherejwe gufata iri tegeko." },
  "Driver is delivering to your customer.": { en: "Driver is delivering to your customer.", fr: "Le chauffeur livre votre client.", rw: "Umushoferi arageza ku mukiriya wawe." },
  "Decline order": { en: "Decline order", fr: "Refuser la commande", rw: "Anga itegeko" },
  "Deliveries": { en: "Deliveries", fr: "Livraisons", rw: "Ibyagejejwe" },
  "Every package you've sent through Zana.": { en: "Every package you've sent through Zana.", fr: "Tous les colis que vous avez envoyés avec Zana.", rw: "Amapaki yose wohereje ukoresheje Zana." },
  "Loading…": { en: "Loading…", fr: "Chargement…", rw: "Birimo gutegurwa…" },
  "No deliveries yet.": { en: "No deliveries yet.", fr: "Aucune livraison pour le moment.", rw: "Nta byo kugeza birabaho." },
  "Finding a courier": { en: "Finding a courier", fr: "Recherche d’un coursier", rw: "Turimo gushaka umutwara" },
  "Courier assigned": { en: "Courier assigned", fr: "Coursier attribué", rw: "Umutwara yahawe akazi" },
  "On the way": { en: "On the way", fr: "En route", rw: "Ari mu nzira" },
  "Rider": { en: "Rider", fr: "Coursier", rw: "Umumotari" },
  "Food & Drinks": { en: "Food & Drinks", fr: "Nourriture et boissons", rw: "Ibiryo n’ibinyobwa" },
  "Gifts": { en: "Gifts", fr: "Cadeaux", rw: "Impano" },
  "General Goods": { en: "General Goods", fr: "Produits généraux", rw: "Ibicuruzwa rusange" },
  "My Products": { en: "My Products", fr: "Mes produits", rw: "Ibicuruzwa byanjye" },
  "New products go to admin for approval before they're visible.": { en: "New products go to admin for approval before they're visible.", fr: "Les nouveaux produits sont envoyés à l’administration pour approbation avant leur publication.", rw: "Ibicuruzwa bishya byoherezwa ku buyobozi kugira ngo byemezwe mbere yo kugaragara." },
  "Add Product": { en: "Add Product", fr: "Ajouter un produit", rw: "Ongeraho igicuruzwa" },
  "New Product": { en: "New Product", fr: "Nouveau produit", rw: "Igicuruzwa gishya" },
  "Product name": { en: "Product name", fr: "Nom du produit", rw: "Izina ry’igicuruzwa" },
  "Description (optional)": { en: "Description (optional)", fr: "Description (facultatif)", rw: "Ibisobanuro (si ngombwa)" },
  "Price (RWF)": { en: "Price (RWF)", fr: "Prix (RWF)", rw: "Igiciro (RWF)" },
  "Stock": { en: "Stock", fr: "Stock", rw: "Ububiko" },
  "Add product photo": { en: "Add product photo", fr: "Ajouter une photo du produit", rw: "Ongeraho ifoto y’igicuruzwa" },
  "Submitting…": { en: "Submitting…", fr: "Envoi…", rw: "Birimo koherezwa…" },
  "Submit for Review": { en: "Submit for Review", fr: "Soumettre pour examen", rw: "Ohereza ngo bisuzumwe" },
  "Cancel": { en: "Cancel", fr: "Annuler", rw: "Hagarika" },
  "Approved": { en: "Approved", fr: "Approuvé", rw: "Byemejwe" },
  "Rejected": { en: "Rejected", fr: "Rejeté", rw: "Byanzwe" },
  "Disabled": { en: "Disabled", fr: "Désactivé", rw: "Byahagaritswe" },
  "No products yet. Add your first one!": { en: "No products yet. Add your first one!", fr: "Aucun produit. Ajoutez votre premier !", rw: "Nta bicuruzwa birabaho. Ongeraho icya mbere!" },
  "Available balance": { en: "Available balance", fr: "Solde disponible", rw: "Amafaranga ahari" },
  "Withdraw to MoMo": { en: "Withdraw to MoMo", fr: "Retirer vers MoMo", rw: "Kura kuri MoMo" },
  "Transaction History": { en: "Transaction History", fr: "Historique des transactions", rw: "Amateka y’ibikorwa" },
  "No transactions yet.": { en: "No transactions yet.", fr: "Aucune transaction pour le moment.", rw: "Nta bikorwa birabaho." },
  "Withdraw Funds": { en: "Withdraw Funds", fr: "Retirer des fonds", rw: "Kura amafaranga" },
  "Amount (RWF)": { en: "Amount (RWF)", fr: "Montant (RWF)", rw: "Amafaranga (RWF)" },
  "MoMo phone number": { en: "MoMo phone number", fr: "Numéro MoMo", rw: "Nimero ya MoMo" },
  "Processing...": { en: "Processing...", fr: "Traitement…", rw: "Biratunganywa…" },
  "Withdraw": { en: "Withdraw", fr: "Retirer", rw: "Kura amafaranga" },
  "Minimum withdrawal is 10,000 RWF": { en: "Minimum withdrawal is 10,000 RWF", fr: "Le retrait minimum est de 10 000 RWF", rw: "Amafaranga make yo gukuramo ni 10,000 RWF" },
  "Insufficient balance": { en: "Insufficient balance", fr: "Solde insuffisant", rw: "Amafaranga ahari ntabwo ahagije" },
  "Enter your MoMo phone number": { en: "Enter your MoMo phone number", fr: "Entrez votre numéro MoMo", rw: "Andika nimero yawe ya MoMo" },
  "Withdrawal failed": { en: "Withdrawal failed", fr: "Le retrait a échoué", rw: "Gukuramo amafaranga byanze" },
  "Credit": { en: "Credit", fr: "Crédit", rw: "Amafaranga yinjiye" },
  "Withdrawal": { en: "Withdrawal", fr: "Retrait", rw: "Gukuramo amafaranga" },
  "Agent at": { en: "Agent at", fr: "Agent chez", rw: "Umukozi kuri" },
  "No orders waiting": { en: "No orders waiting", fr: "Aucune commande en attente", rw: "Nta mategeko ategereje" },
  "What did you actually pay for each item? Leave blank if it matched the stall price.": { en: "What did you actually pay for each item? Leave blank if it matched the stall price.", fr: "Quel prix avez-vous réellement payé pour chaque article ? Laissez vide s’il correspondait au prix du stand.", rw: "Watanze angahe kuri buri gicuruzwa? Siga ubusa niba ari kimwe n’igiciro cyo ku isoko." },
  "Could not add the item": { en: "Could not add the item", fr: "Impossible d’ajouter l’article", rw: "Ntibyashobotse kongeraho igicuruzwa" },
  "Start shopping": { en: "Start shopping", fr: "Commencer les achats", rw: "Tangira guhaha" },
  "Today’s items": { en: "Today’s items", fr: "Articles du jour", rw: "Ibicuruzwa by’uyu munsi" },
  "Wallet": { en: "Wallet", fr: "Portefeuille", rw: "Amafaranga" },
  "Customer": { en: "Customer", fr: "Client", rw: "Umukiriya" },
  "Item name, e.g. Tomatoes (1kg)": { en: "Item name, e.g. Tomatoes (1kg)", fr: "Nom de l’article, ex. Tomates (1 kg)", rw: "Izina ry’igicuruzwa, urugero Inyanya (1kg)" },
  "Selling price in RWF": { en: "Selling price in RWF", fr: "Prix de vente en RWF", rw: "Igiciro cyo kugurisha muri RWF" },
  "Normal stall price (optional — for your margin split)": { en: "Normal stall price (optional — for your margin split)", fr: "Prix normal du stand (facultatif — pour le calcul de votre marge)", rw: "Igiciro gisanzwe ku isoko (si ngombwa — mu kubara inyungu yawe)" },
  "Saving…": { en: "Saving…", fr: "Enregistrement…", rw: "Birimo kubikwa…" },
  "Add to today’s list": { en: "Add to today’s list", fr: "Ajouter à la liste du jour", rw: "Ongeraho ku rutonde rw’uyu munsi" },
  "Confirm ready for pickup": { en: "Confirm ready for pickup", fr: "Confirmer prêt pour le retrait", rw: "Emeza ko biteguye gufatwa" },
  "Rider on the way": { en: "Rider on the way", fr: "Coursier en route", rw: "Umumotari ari mu nzira" },
  "List an item": { en: "List an item", fr: "Ajouter un article", rw: "Shyiraho igicuruzwa" },
  "Nothing listed yet. Add what is on the stalls today.": { en: "Nothing listed yet. Add what is on the stalls today.", fr: "Rien n’est encore listé. Ajoutez ce qui est disponible sur les stands aujourd’hui.", rw: "Nta kintu kirashyirwa ku rutonde. Ongeraho ibiri ku masoko uyu munsi." },
  "Welcome back": { en: "Welcome back", fr: "Bon retour", rw: "Murakaza neza" },
  "Your shop card": { en: "Your shop card", fr: "Carte de votre boutique", rw: "Ikarita y’iduka ryawe" },
  "Logo": { en: "Logo", fr: "Logo", rw: "Ikirango" },
  "Storefront photo": { en: "Storefront photo", fr: "Photo de la boutique", rw: "Ifoto y’iduka" },
  "Shops with a photo get noticeably more orders.": { en: "Shops with a photo get noticeably more orders.", fr: "Les boutiques avec une photo reçoivent nettement plus de commandes.", rw: "Amaduka afite ifoto abona amategeko menshi." },
  "Earnings & settlements": { en: "Earnings & settlements", fr: "Gains et règlements", rw: "Amafaranga n’imitunganyirize" },
  "View earnings": { en: "View earnings", fr: "Voir les gains", rw: "Reba amafaranga winjije" },
  "RWF balance": { en: "RWF balance", fr: "Solde RWF", rw: "Amafaranga RWF" },
  "Pending orders": { en: "Pending orders", fr: "Commandes en attente", rw: "Amategeko ategereje" },
  "Active deliveries": { en: "Active deliveries", fr: "Livraisons actives", rw: "Ibyagezwaho bikora" },
  "Total deliveries": { en: "Total deliveries", fr: "Total des livraisons", rw: "Ibyagejejwe byose" },
  "Set your business location": { en: "Set your business location", fr: "Définissez l’emplacement de votre entreprise", rw: "Shyiraho aho ubucuruzi bwawe buri" },
  "This lets us calculate delivery fees for your customers accurately.": { en: "This lets us calculate delivery fees for your customers accurately.", fr: "Cela nous permet de calculer précisément les frais de livraison de vos clients.", rw: "Ibi bidufasha kubara neza amafaranga yo kugeza ku bakiriya bawe." },
  "Quick Actions": { en: "Quick Actions", fr: "Actions rapides", rw: "Ibikorwa byihuse" },
  "Send a Package": { en: "Send a Package", fr: "Envoyer un colis", rw: "Ohereza ipaki" },
  "Request a Zana courier": { en: "Request a Zana courier", fr: "Demander un coursier Zana", rw: "Saba umutwara wa Zana" },
  "Manage your listings": { en: "Manage your listings", fr: "Gérez vos produits", rw: "Genzura ibicuruzwa byawe" },
  "Orders": { en: "Orders", fr: "Commandes", rw: "Ibyatumijwe" },
  "Account pending approval": { en: "Account pending approval", fr: "Compte en attente d’approbation", rw: "Konti itegereje kwemezwa" },
  "Earnings": { en: "Earnings", fr: "Gains", rw: "Amafaranga winjije" },
  "Your merchant settlement ledger": { en: "Your merchant settlement ledger", fr: "Votre registre de règlement marchand", rw: "Amateka y’imitunganyirize y’umucuruzi" },
  "Could not load earnings.": { en: "Could not load earnings.", fr: "Impossible de charger les gains.", rw: "Ntibyashobotse kubona amafaranga winjije." },
  "Withdrawable wallet balance": { en: "Withdrawable wallet balance", fr: "Solde du portefeuille retirable", rw: "Amafaranga ushobora gukuramo" },
  "Settled merchant earnings": { en: "Settled merchant earnings", fr: "Gains marchand réglés", rw: "Amafaranga y’umucuruzi yishyuwe" },
  "Zana commission": { en: "Zana commission", fr: "Commission Zana", rw: "Komisiyo ya Zana" },
  "Settlement": { en: "Settlement", fr: "Règlement", rw: "Itunganywa" },
  "Sale": { en: "Sale", fr: "Vente", rw: "Igurishwa" },
  "You receive": { en: "You receive", fr: "Vous recevez", rw: "Uhabwa" },
  "No settled sales yet.": { en: "No settled sales yet.", fr: "Aucune vente réglée pour le moment.", rw: "Nta gurisha ryishyuwe rirabaho." },
  "Delivery requested": { en: "Delivery requested", fr: "Livraison demandée", rw: "Kohereza byasabwe" },
  "A Zana courier will be assigned shortly. You can track it on the Deliveries page.": { en: "A Zana courier will be assigned shortly. You can track it on the Deliveries page.", fr: "Un coursier Zana sera bientôt attribué. Vous pouvez le suivre sur la page Livraisons.", rw: "Umutwara wa Zana azahabwa akazi vuba. Ushobora kumukurikirana ku rupapuro rw’Ibyagejejwe." },
  "Create another delivery": { en: "Create another delivery", fr: "Créer une autre livraison", rw: "Tangira ikindi kohereza" },
  "New delivery": { en: "New delivery", fr: "Nouvelle livraison", rw: "Kohereza gushya" },
  "Send a package to your customer.": { en: "Send a package to your customer.", fr: "Envoyez un colis à votre client.", rw: "Ohereza ipaki ku mukiriya wawe." },
  "What are you sending?": { en: "What are you sending?", fr: "Qu’envoyez-vous ?", rw: "Urimo kohereza iki?" },
  "Approximate weight": { en: "Approximate weight", fr: "Poids approximatif", rw: "Uburemere bugereranyijwe" },
  "Photo of the item": { en: "Photo of the item", fr: "Photo de l’article", rw: "Ifoto y’ikintu" },
  "Upload a photo": { en: "Upload a photo", fr: "Téléverser une photo", rw: "Ongeraho ifoto" },
  "Pickup location": { en: "Pickup location", fr: "Lieu de prise en charge", rw: "Aho ufatira" },
  "Delivery location": { en: "Delivery location", fr: "Lieu de livraison", rw: "Aho kugeza" },
  "Customer can't explain their address? Ask them to send their Zana location code.": { en: "Customer can't explain their address? Ask them to send their Zana location code.", fr: "Le client ne peut pas expliquer son adresse ? Demandez-lui d’envoyer son code de localisation Zana.", rw: "Umukiriya ntashobora gusobanura aho ari? Musabe akohereze kode y’aho ari ya Zana." },
  "Receiver": { en: "Receiver", fr: "Destinataire", rw: "Uwakira" },
  "Delivery fee": { en: "Delivery fee", fr: "Frais de livraison", rw: "Amafaranga yo kugeza" },
  "Requesting…": { en: "Requesting…", fr: "Demande en cours…", rw: "Gusaba birakomeje…" },
  "Request Delivery": { en: "Request Delivery", fr: "Demander une livraison", rw: "Saba kohereza" },
  "Zana Business": { en: "Zana Business", fr: "Zana Business", rw: "Zana Business" },
  "Merchant Portal": { en: "Merchant Portal", fr: "Portail marchand", rw: "Urubuga rw’umucuruzi" },
  "Sign in": { en: "Sign in", fr: "Se connecter", rw: "Injira" },
  "Sign in as a merchant or market agent": { en: "Sign in as a merchant or market agent", fr: "Connectez-vous en tant que commerçant ou agent de marché", rw: "Injira nk’umucuruzi cyangwa umukozi wo ku isoko" },
  "Email address": { en: "Email address", fr: "Adresse e-mail", rw: "Aderesi ya imeyili" },
  "Password": { en: "Password", fr: "Mot de passe", rw: "Ijambobanga" },
  "Don't have an account? Contact": { en: "Don't have an account? Contact", fr: "Vous n’avez pas de compte ? Contactez", rw: "Nta konti ufite? Hamagara" },
  "Demo: merchant@zana.rw / merchant123": { en: "Demo: merchant@zana.rw / merchant123", fr: "Démo : merchant@zana.rw / merchant123", rw: "Urugero: merchant@zana.rw / merchant123" },
  "Refresh": { en: "Refresh", fr: "Actualiser", rw: "Ongera usubiremo" },
  "Agent wallet": { en: "Agent wallet", fr: "Portefeuille de l’agent", rw: "Umufuka w’umukozi" },
  "Today’s orders": { en: "Today’s orders", fr: "Commandes du jour", rw: "Ibyatumijwe uyu munsi" },
  "Open any order for the complete receipt and timeline.": { en: "Open any order for the complete receipt and timeline.", fr: "Ouvrez une commande pour le reçu et la chronologie complète.", rw: "Fungura itegeko iryo ari ryo ryose urebe inyemezabuguzi n’amateka yose." },
  "View all": { en: "View all", fr: "Voir tout", rw: "Reba byose" },
  "Earned commission released after delivery.": { en: "Earned commission released after delivery.", fr: "La commission gagnée est libérée après la livraison.", rw: "Komisiyo yinjijwe irekurwa nyuma yo kugeza." },
  "Purchasing funds in active orders": { en: "Purchasing funds in active orders", fr: "Fonds d’achat dans les commandes actives", rw: "Amafaranga yo kugura ari mu byatumijwe bikora" },
  "Pending commission": { en: "Pending commission", fr: "Commission en attente", rw: "Komisiyo itegereje" },
  "Item issues": { en: "Item issues", fr: "Problèmes d’article", rw: "Ibibazo by’ibicuruzwa" },
  "Shop, resolve unavailable items and prepare packages for pickup.": { en: "Shop, resolve unavailable items and prepare packages for pickup.", fr: "Achetez, gérez les articles indisponibles et préparez les colis.", rw: "Gura, kora ku bicuruzwa bidahari kandi utegure amapaki." },
  "Packages a Zana rider has been assigned to or has picked up from your market.": { en: "Packages a Zana rider has been assigned to or has picked up from your market.", fr: "Colis attribués à un coursier Zana ou déjà retirés de votre marché.", rw: "Amapaki yahawe umumotari wa Zana cyangwa yafashwe ku isoko ryawe." },
  "What you can physically source at the market today.": { en: "What you can physically source at the market today.", fr: "Ce que vous pouvez réellement trouver au marché aujourd’hui.", rw: "Ibyo ushobora kubona ku isoko uyu munsi." },
  "Recent wallet activity": { en: "Recent wallet activity", fr: "Activité récente du portefeuille", rw: "Ibikorwa biheruka ku mufuka" },
  "Purchasing funds": { en: "Purchasing funds", fr: "Fonds d’achat", rw: "Amafaranga yo kugura" },
  "Ready for rider": { en: "Ready for rider", fr: "Prêt pour le coursier", rw: "Biteguye umumotari" },
  "Picked up": { en: "Picked up", fr: "Retiré", rw: "Byafashwe" },
  "Refunded to customer": { en: "Refunded to customer", fr: "Remboursé au client", rw: "Yasubijwe umukiriya" },
  "Authorized": { en: "Authorized", fr: "Autorisé", rw: "Yemejwe" },
  "Withdrawn": { en: "Withdrawn", fr: "Retiré", rw: "Yakuweho" },
  "Actual spend": { en: "Actual spend", fr: "Dépense réelle", rw: "Amafaranga yakoreshejwe" },
  "Customer refund": { en: "Customer refund", fr: "Remboursement client", rw: "Amafaranga asubijwe umukiriya" },
  "Recovered from agent": { en: "Recovered from agent", fr: "Récupéré auprès de l’agent", rw: "Yakuwe ku mukozi" },
  "Registered number": { en: "Registered number", fr: "Numéro enregistré", rw: "Numero yanditswe" },
  "Latitude / Longitude": { en: "Latitude / Longitude", fr: "Latitude / Longitude", rw: "Latitude / Longitude" },
  "Open in Maps": { en: "Open in Maps", fr: "Ouvrir dans Maps", rw: "Fungura muri Maps" },
  "Mark ready for pickup": { en: "Mark ready for pickup", fr: "Marquer prêt pour le retrait", rw: "Shyira ku mwanya wo gufatwa" },
  "Waiting for rider": { en: "Waiting for rider", fr: "En attente du coursier", rw: "Gutegereza umumotari" },
  "Rider handoff": { en: "Rider handoff", fr: "Remise au coursier", rw: "Guha umumotari" },
};

export function t(key: string, lang: Lang): string {
  return UI[key]?.[lang] ?? key;
}
